package com.assistanz.fogpanel;

/**
 *
 * @author gowtham
 */
public enum FogPanelService {
    
    //VM SERVICE ACTION
    VM_CREATE,
    VM_LIST,
    VM_START,
    VM_STOP,
    VM_REBOOT,
    VM_VIEW_CONSOLE,
    VM_DELETE,
    VM_RESTORT,
    VM_CHANGE_PLAN,
    VM_RESET_PASSWORD,
    VM_UPDATE_HOSTNAME,
    VM_MIGRATE,
    VM_ACQUIRE_IP,
    VM_REVOKE_IP,
    VM_ATTACH_ISO,
    VM_DETACH_ISO,
    
    //VOLUME SERVICE ACTION
    VOLUME_CREATE,
    VOLUME_ATTACH,
    VOLUME_RESIZE,
    VOLUME_DETACH,
    VOLUME_DELETE,
    
    //SNAPSHOT SERVICE ACTION
    SNAPSHOT_CREATE,
    SNAPSHOT_DELETE,
    
    //VM SNAPSHOT SERVICE ACTION
    VM_SNAPSHOT_CREATE,
    VM_SNAPSHOT_REVERT,
    VM_SNAPSHOT_DELETE,
    
    //SNAPSHOT POLICY SERVICE
    SNAPSHOT_POLICY_CREATE, 
    SNAPSHOT_POLICY_DELETE,
    SNAPSHOT_POLICY_UPDATE,
    
    //SECURITY GROUP SERVICE ACTION
    SECURITY_GROUP_CREATE,
    SECURITY_GROUP_DELETE,
    SECURITY_GROUP_ADD_INGRESS,
    SECURITY_GROUP_ADD_EGRESS,
    SECURITY_GROUP_DELETE_INGRESS,
    SECURITY_GROUP_DELETE_EGRESS,
    
    //ACCOUNT SERVICE
    ACCOUNT_SIGNUP,
    
    // SSH KEY SERVICE ACTION
    SSH_KEY_CREATE,
    SSH_KEY_DELETE,
    SSH_KEY_RESET,
    
    //OFFERING SERVICE
    OFFERING_ADD,
    OFFERING_UPDATE,
    OFFERING_DELETE,
    OFFERING_DISABLE,
    
    //BILLING SERVICE ACTION
    INVOICE_ITEM_ADD,
    PAYMENT_ADD,
    SAVE_CARD,
    RECURRING_ITEM_ADD,
    TAX_CREATE,
    TAX_UPDATE,
    TAX_DELETE,
    RECURRING_ITEM_DELETE,
    RECURRING_TIEM_UPDATE,
    BILLABLE_ITEM_UPDATE,
    
    //USAGE SERVICE
    USAGE_RECORD_ADD
}
