/*
	Copyright (c) 2004-2012, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

//>>built
define("dojo/request/script","module,./watch,./util,../_base/array,../_base/lang,../on,../dom,../dom-construct,../has,../_base/window".split(","),function(l,m,h,n,o,p,q,r,j,s){function t(a,b){a.canDelete&&f._remove(a.id,b.options.frameDoc,!0)}function u(a){g&&g.length&&(n.forEach(g,function(a){f._remove(a.id,a.frameDoc);a.frameDoc=null}),g=[]);return a.options.jsonp?!a.data:!0}function v(){return!!this.scriptLoaded}function w(a){return(a=a.options.checkString)&&eval("typeof("+a+') !== "undefined"')}
function x(a,b){if(this.canDelete){var c=this.response.options;g.push({id:this.id,frameDoc:c.ioArgs?c.ioArgs.frameDoc:c.frameDoc});if(c.ioArgs)c.ioArgs.frameDoc=null;c.frameDoc=null}b?this.reject(b):this.resolve(a)}function f(a,b,c){var d=h.parseArgs(a,h.deepCopy({},b)),a=d.url,b=d.options,e=h.deferred(d,t,u,b.jsonp?null:b.checkString?w:v,x);o.mixin(e,{id:k+y++,canDelete:!1});if(b.jsonp)RegExp("[?&]"+b.jsonp+"=").test(a)||(a+=(~a.indexOf("?")?"&":"?")+b.jsonp+"="+(b.frameDoc?"parent.":"")+k+"_callbacks."+
e.id),e.canDelete=!0,i[e.id]=function(a){d.data=a;e.handleResponse(d)};h.notify&&h.notify.emit("send",d,e.promise.cancel);if(!b.canAttach||b.canAttach(e)){var g=f._attach(e.id,a,b.frameDoc);if(!b.jsonp&&!b.checkString)var j=p(g,z,function(a){if("load"===a.type||A.test(g.readyState))j.remove(),e.scriptLoaded=a})}m(e);return c?e:e.promise}j.add("script-readystatechange",function(a,b){return"undefined"!==typeof b.createElement("script").onreadystatechange&&("undefined"===typeof a.opera||"[object Opera]"!==
a.opera.toString())});var k=l.id.replace(/[\/\.\-]/g,"_"),y=0,z=j("script-readystatechange")?"readystatechange":"load",A=/complete|loaded/,i=this[k+"_callbacks"]={},g=[];f.get=f;f._attach=function(a,b,c){var c=c||s.doc,d=c.createElement("script");d.type="text/javascript";d.src=b;d.id=a;d.async=!0;d.charset="utf-8";return c.getElementsByTagName("head")[0].appendChild(d)};f._remove=function(a,b,c){r.destroy(q.byId(a,b));i[a]&&(c?i[a]=function(){delete i[a]}:delete i[a])};f._callbacksProperty=k+"_callbacks";
return f});