//>>built
define("FogPanel/VerticalMenuBar","require,dojo/_base/declare,dojo/has,dojo/keys,dojo/ready,dijit/_Widget,dijit/form/Button,dijit/form/Select,dojo/dom-construct,dojo/dom-class,dojo/fx,dojo/_base/connect,dojo/request/registry,dijit/_KeyNavContainer,dijit/_TemplatedMixin,dojo/NodeList-traverse".split(","),function(o,j,p,q,r,k,s,l,h,c,g,i,m,n){return j("FogPanel.VerticalMenuBar",[k,n,m],{templateString:'<div class="sidebar-nav" tabIndex="${tabIndex}" data-dojo-attach-point="containerNode"></div>',baseClass:"sidebar-nav",
serviceMenuId:"",options:!1,filterOption:!1,selectOptionContent:"",backtoDashboardLabel:"",selectBoxValue:"",_subscriptionHandle:"",__handle:"",postCreate:function(){window.widget=this;this.inherited(arguments);dojo.query(".sidebar-nav .dashboard-menu").children();var e=dojo.query(".sidebar-nav .dashboard-menu li .dropdown-toggle");dojo.query(".sidebar-nav .dashboard-menu li .submenu li a");if(!0===this.options){var f=h.toDom('<a class="btn-glow primary new-product overflowLabel back_button">'+this.backtoDashboardLabel+
"</a>");this.containerNode.appendChild(f);f.onclick=function(){widget.onBackButtonclick()};!0===this.filterOption&&(f=h.toDom("<div></div>"),this.containerNode.appendChild(f),new l({value:widget.selectBoxValue,store:widget.selectOptionContent,"class":"vpn_box",onChange:function(){widget.onSelectBoxChange(this)}},f))}dojo.forEach(e,function(a){var d=dojo.query(a).next()[0];g.wipeOut({node:d,duration:500,onEnd:function(){c.remove(d,"active")}}).play();a.onclick=function(){}})},onServiceMenuItemClick:function(){},
onOtherMenuItemClick:function(){},onSelectBoxChange:function(){},onBackButtonclick:function(){},populateMenu:function(c){var f=this,a="",d="",a="<ul class='dashboard-menu'>";dojo.forEach(c,function(b,c){d="main_menu_"+(c+1);!0===b.action?(f.serviceMenuId=d,a+="<li><a id="+d+" class= 'mainMenu'onclick = widget.onServiceMenuItemClick()><i class= "+b.iconClass+"></i><span>"+b.menuItemName+"</span><i class="+b.dropdownIcon+"></i></a>"):a+="<li><a id="+d+" class= 'mainMenu "+b.aTagClasses+"'href="+b.href+
" onclick=widget.onOtherMenuItemClick()><i class= "+b.iconClass+"></i><span>"+b.menuItemName+"</span><i class="+b.dropdownIcon+"></i></a>";!0===b.subMenu&&(a+="<ul class='submenu' id='instanceMenu'>",dojo.forEach(b.submenuContent,function(b){a+="<li><a href="+b.href+" onclick=widget.onOtherMenuItemClick()>"+b.subMenuItemName+"</a></li>"}),a+="</ul>");a+="</li>"});a+="</ul>";h.place(a,window.widget.containerNode)},onSubMenuItemClick:function(e,f){var a=dojo.query(".sidebar-nav .dashboard-menu li .submenu li a");
dojo.forEach(a,function(a,b){f===b?c.add(a,"bolder"):c.remove(a,"bolder")})},onMenuItemClick:function(e,f){var a=dojo.query(e).next()[0],d=dojo.query(e).parent()[0];a&&("active"===a.className.split(" ")[1]?g.wipeOut({node:a,duration:500,onEnd:function(){c.remove(a,"active");c.remove(d,"active")}}).play():(c.add(a,"active"),c.add(d,"active"),g.wipeIn({node:a,duration:500}).play()));var b=dojo.query(".sidebar-nav .dashboard-menu li .dropdown-toggle");dojo.forEach(b,function(a,b){if(b!==f){var d=dojo.query(a).next()[0],
e=dojo.query(a).parent()[0];c.remove(e,"activeMenu");c.remove(e,"active");d&&g.wipeOut({node:d,duration:500,onEnd:function(){c.remove(d,"active")}}).play()}else e=dojo.query(a).parent()[0],c.add(e,"active")});b=dojo.query(".sidebar-nav .dashboard-menu li .submenu li a");dojo.forEach(b,function(a){c.remove(a,"bolder")});b=dojo.query(".sidebar-nav .dashboard-menu li .singleMenu");dojo.forEach(b,function(a){a=dojo.query(a).parent()[0];c.remove(a,"active")})},onMainMenuItemClick:function(e){var f=dojo.query(".dashboard-menu a");
dojo.forEach(f,function(a){if(e.hash===a.hash)a=dojo.query(a).parent()[0],c.add(a,"active");else{var d=dojo.query(a).next()[0],b=dojo.query(a).parent()[0];d?g.wipeOut({node:d,duration:500,onEnd:function(){c.remove(d,"active");c.remove(b,"active")}}).play():(a=dojo.query(a).parent()[0],c.remove(a,"active"))}})},highLightSelectedMenuItem:function(e){var f=dojo.query(".dashboard-menu a"),a=dojo.query(".sidebar-nav .dashboard-menu li .dropdown-toggle");dojo.forEach(f,function(d){if(d.hash===e)if("mainMenu"===
d.className.split(" ")[0])if(dojo.query(d).next()[0])dojo.forEach(a,function(a,d){if(a.hash===e)widget.onMenuItemClick(a,d)});else widget.onMainMenuItemClick(d);else d=dojo.query(".sidebar-nav .dashboard-menu li .submenu li a"),dojo.forEach(d,function(b,d){if(b.hash===e){var f=dojo.query(b).parent().parent()[0],h=dojo.query(f).prev()[0];dojo.forEach(a,function(a){if(a.hash===h.hash){var a=f.className.split(" "),e=dojo.query(f).parent()[0];if("active"===a[1])widget.onSubMenuItemClick(b,d);else c.add(f,
"active"),g.wipeIn({node:f,duration:500,onBegin:function(){}}).play(),widget.onSubMenuItemClick(b,d),c.add(e,"active")}else a=dojo.query(a).next()[0],e=dojo.query(a).parent()[0],c.remove(e,"active"),c.remove(a,"active")})}})})},onLiClick:function(e,f){var a=dojo.query(".sidebar-nav .dashboard-menu").children();dojo.forEach(a,function(a,b){b===f?c.add(a,"active"):c.remove(a,"active")});a=dojo.query(".sidebar-nav .dashboard-menu .submenu").children();dojo.forEach(a,function(a,b){a.onclick=function(){widget.onSubLinkClick(this,
b)}})},onSubLinkClick:function(e,f){var a=dojo.query(".sidebar-nav .dashboard-menu .submenu").children();dojo.forEach(a,function(a,b){var e=a.childNodes;f===b?c.add(e[0],"bolder"):c.remove(e[0],"bolder")})},subscribe:function(){widget._subscriptionHandle=i.subscribe("/FogPanel/event/route/changed",function(c){widget.highLightSelectedMenuItem(c)})},unsubscribe:function(){i.unsubscribe(widget._subscriptionHandle)},disable:function(){c.add(this.containerNode,"disabled")},enable:function(){c.remove(this.containerNode,
"disabled")}})});