databaseChangeLog = {
    
        changeSet(author: "santhosh", id: "changelog.0.1.13") {
        
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 1)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "t1.micro")
                column(name: "family", value: "Micro instances")
                column(name: "ecu", value: "Variable")
                column(name: "physical_processor", value: "Variable")
                column(name: "network_performance", value: "Very Low")
                column(name: "processor_architecture", value: "64-bit, 32-bit")
                column(name: "intel_aes_ni", value: null)
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 0.613)
                column(name: "vcpus", valueNumeric: 1)
                column(name: "clock_speed", valueNumeric:null )
                column(name: "instance_store", value:"EBS only" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 2)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "t2.micro")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "Variable")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "Low to Moderate")
                column(name: "processor_architecture", value: "64-bit, 32-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 1)
                column(name: "vcpus", valueNumeric: 1)
                column(name: "clock_speed", valueNumeric:2.5 )
                column(name: "instance_store", value:"EBS only" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 3)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "t2.small")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "Variable")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "Low to Moderate")
                column(name: "processor_architecture", value: "64-bit, 32-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 2)
                column(name: "vcpus", valueNumeric: 1)
                column(name: "clock_speed", valueNumeric:2.5 )
                column(name: "instance_store", value:"EBS only" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 4)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "t2.medium")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "Variable")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "Low to Moderate")
                column(name: "processor_architecture", value: "64-bit, 32-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 4)
                column(name: "vcpus", valueNumeric: 2)
                column(name: "clock_speed", valueNumeric:2.5 )
                column(name: "instance_store", value:"EBS only" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 5)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m3.medium")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "3")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 3.75)
                column(name: "vcpus", valueNumeric: 1)
                column(name: "clock_speed", valueNumeric:2.5 )
                column(name: "instance_store", value:"1 x 4 (SSD)" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 6)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m3.large")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "6.5")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 7.5)
                column(name: "vcpus", valueNumeric: 2)
                column(name: "clock_speed", valueNumeric:2.5 )
                column(name: "instance_store", value:"1 x 32 (SSD)" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 7)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m3.xlarge")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "13")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 15)
                column(name: "vcpus", valueNumeric: 4)
                column(name: "clock_speed", valueNumeric:2.5 )
                column(name: "instance_store", value:"2 x 40 (SSD)" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 8)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m3.2xlarge")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "26")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 30)
                column(name: "vcpus", valueNumeric: 8)
                column(name: "clock_speed", valueNumeric:2.5 )
                column(name: "instance_store", value:"2 x 80 (SSD)" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 9)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m1.small")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "1")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "low")
                column(name: "processor_architecture", value: "64-bit,32-bit")
                column(name: "intel_aes_ni", value: null)
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 1.7)
                column(name: "vcpus", valueNumeric: 1)
                column(name: "clock_speed", valueNumeric:null )
                column(name: "instance_store", value:"1x160" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 10)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m1.medium")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "2")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit,32-bit")
                column(name: "intel_aes_ni", value: null)
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 3.7)
                column(name: "vcpus", valueNumeric: 1)
                column(name: "clock_speed", valueNumeric:null )
                column(name: "instance_store", value:"1x410" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 11)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m1.large")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "4")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: null)
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 7.5)
                column(name: "vcpus", valueNumeric: 2)
                column(name: "clock_speed", valueNumeric:null )
                column(name: "instance_store", value:"2x420" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 12)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m1.xlarge")
                column(name: "family", value: "General purpose")
                column(name: "ecu", value: "8")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: null)
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 15)
                column(name: "vcpus", valueNumeric: 4)
                column(name: "clock_speed", valueNumeric:null )
                column(name: "instance_store", value:"4x420" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 13)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c4.large")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "8")
                column(name: "physical_processor", value: "Intel Xeon E5-2666v3")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 3.75)
                column(name: "vcpus", valueNumeric: 2)
                column(name: "clock_speed", valueNumeric:2.9 )
                column(name: "instance_store", value:"EBS only" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 14)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c4.xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "16")
                column(name: "physical_processor", value: "Intel Xeon E5-2666v3")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 7.5)
                column(name: "vcpus", valueNumeric: 4)
                column(name: "clock_speed", valueNumeric:2.9 )
                column(name: "instance_store", value:"EBS only" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 15)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c4.2xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "31")
                column(name: "physical_processor", value: "Intel Xeon E5-2666v3")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 15)
                column(name: "vcpus", valueNumeric: 8)
                column(name: "clock_speed", valueNumeric:2.9 )
                column(name: "instance_store", value:"EBS only" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 16)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c4.4xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "62")
                column(name: "physical_processor", value: "Intel Xeon E5-2666v3")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 30)
                column(name: "vcpus", valueNumeric: 16)
                column(name: "clock_speed", valueNumeric:2.9 )
                column(name: "instance_store", value:"EBS only" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 17)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c4.8xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "132")
                column(name: "physical_processor", value: "Intel Xeon E5-2666v3")
                column(name: "network_performance", value: "10 Gigabit")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 60)
                column(name: "vcpus", valueNumeric: 36)
                column(name: "clock_speed", valueNumeric:2.9 )
                column(name: "instance_store", value:"EBS only" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 18)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c3.large")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "7")
                column(name: "physical_processor", value: "Intel Xeon E5-2680v2")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 3.75)
                column(name: "vcpus", valueNumeric: 2)
                column(name: "clock_speed", valueNumeric:2.8 )
                column(name: "instance_store", value:"2 x 16 (SSD)" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 19)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c3.xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "14")
                column(name: "physical_processor", value: "Intel Xeon E5-2680v2")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 7.5)
                column(name: "vcpus", valueNumeric: 4)
                column(name: "clock_speed", valueNumeric:2.8 )
                column(name: "instance_store", value:"2 x 40 (SSD)" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 20)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c3.2xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "28")
                column(name: "physical_processor", value: "Intel Xeon E5-2680v2")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 15)
                column(name: "vcpus", valueNumeric: 8)
                column(name: "clock_speed", valueNumeric:2.8 )
                column(name: "instance_store", value:"2 x 80 (SSD)" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 21)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c3.4xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "55")
                column(name: "physical_processor", value: "Intel Xeon E5-2680v2")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 30)
                column(name: "vcpus", valueNumeric: 16)
                column(name: "clock_speed", valueNumeric:2.8 )
                column(name: "instance_store", value:"2 x 160 (SSD)" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 22)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c3.8xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "108")
                column(name: "physical_processor", value: "Intel Xeon E5-2680v2")
                column(name: "network_performance", value: "10 Gigabit")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 60)
                column(name: "vcpus", valueNumeric: 32)
                column(name: "clock_speed", valueNumeric:2.8 )
                column(name: "instance_store", value:"2 x 320 (SSD)" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 23)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c1.medium")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "5")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit,32-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 1.7)
                column(name: "vcpus", valueNumeric: 2)
                column(name: "clock_speed", valueNumeric:null )
                column(name: "instance_store", value:"1 x 350" )
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 24)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "c1.xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "20")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit,32-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 7)
                column(name: "vcpus", valueNumeric: 8)
                column(name: "clock_speed", valueNumeric:null )
                column(name: "instance_store", value:"4 x 420" )
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 25)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "cc2.8xlarge")
                column(name: "family", value: "Compute optimized")
                column(name: "ecu", value: "88")
                column(name: "physical_processor", value: "Intel Xeon E5-2670")
                column(name: "network_performance", value: "10 Gigabit")
                column(name: "processor_architecture", value: "64-bit,32-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 60.5)
                column(name: "vcpus", valueNumeric: 32)
                column(name: "clock_speed", valueNumeric:2.6)
                column(name: "instance_store", value:"4 x 840")
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 26)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "g2.2xlarge")
                column(name: "family", value: "GPU instances")
                column(name: "ecu", value: "26")
                column(name: "physical_processor", value: "Intel Xeon E5-2670")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 15)
                column(name: "vcpus", valueNumeric: 8)
                column(name: "clock_speed", valueNumeric:2.6)
                column(name: "instance_store", value:"1 x 60 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 27)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "r3.large")
                column(name: "family", value: "Memory optimized")
                column(name: "ecu", value: "6.5")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 15)
                column(name: "vcpus", valueNumeric: 2)
                column(name: "clock_speed", valueNumeric:2.5)
                column(name: "instance_store", value:"1 x 32 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 28)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "r3.xlarge")
                column(name: "family", value: "Memory optimized")
                column(name: "ecu", value: "13")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 30.5)
                column(name: "vcpus", valueNumeric: 4)
                column(name: "clock_speed", valueNumeric:2.5)
                column(name: "instance_store", value:"1 x 80 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 29)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "r3.2xlarge")
                column(name: "family", value: "Memory optimized")
                column(name: "ecu", value: "26")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 61)
                column(name: "vcpus", valueNumeric: 8)
                column(name: "clock_speed", valueNumeric:2.5)
                column(name: "instance_store", value:"1 x 160 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 30)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "r3.4xlarge")
                column(name: "family", value: "Memory optimized")
                column(name: "ecu", value: "52")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 122)
                column(name: "vcpus", valueNumeric: 16)
                column(name: "clock_speed", valueNumeric:2.5)
                column(name: "instance_store", value:"1 x 320 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 31)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "r3.8xlarge")
                column(name: "family", value: "Memory optimized")
                column(name: "ecu", value: "104")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "10 Gigabit")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 244)
                column(name: "vcpus", valueNumeric: 32)
                column(name: "clock_speed", valueNumeric:2.5)
                column(name: "instance_store", value:"2 x 320 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 32)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m2.xlarge")
                column(name: "family", value: "Memory optimized")
                column(name: "ecu", value: "6.5")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 17.1)
                column(name: "vcpus", valueNumeric: 2)
                column(name: "clock_speed", valueNumeric:null)
                column(name: "instance_store", value:"1 x 420")
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 33)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m2.2xlarge")
                column(name: "family", value: "Memory optimized")
                column(name: "ecu", value: "13")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 34.2)
                column(name: "vcpus", valueNumeric: 4)
                column(name: "clock_speed", valueNumeric:null)
                column(name: "instance_store", value:"1 x 850")
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 34)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "m2.4xlarge")
                column(name: "family", value: "Memory optimized")
                column(name: "ecu", value: "26")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: false)
                column(name: "memory", valueNumeric: 68.4)
                column(name: "vcpus", valueNumeric: 8)
                column(name: "clock_speed", valueNumeric:null)
                column(name: "instance_store", value:"2 x 840")
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 35)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "cr1.8xlarge")
                column(name: "family", value: "Memory optimized")
                column(name: "ecu", value: "88")
                column(name: "physical_processor", value: "Intel Xeon E5-2670")
                column(name: "network_performance", value: "10 Gigabit")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 244)
                column(name: "vcpus", valueNumeric: 32)
                column(name: "clock_speed", valueNumeric:null)
                column(name: "instance_store", value:"2 x 120 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 36)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "i2.xlarge")
                column(name: "family", value: "Storage optimized")
                column(name: "ecu", value: "14")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "Moderate")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 30.5)
                column(name: "vcpus", valueNumeric: 4)
                column(name: "clock_speed", valueNumeric:2.5)
                column(name: "instance_store", value:"1 x 800 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 37)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "i2.2xlarge")
                column(name: "family", value: "Storage optimized")
                column(name: "ecu", value: "27")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 61)
                column(name: "vcpus", valueNumeric: 8)
                column(name: "clock_speed", valueNumeric:2.5)
                column(name: "instance_store", value:"2 x 800 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 38)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "i2.4xlarge")
                column(name: "family", value: "Storage optimized")
                column(name: "ecu", value: "53")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "High")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 122)
                column(name: "vcpus", valueNumeric: 16)
                column(name: "clock_speed", valueNumeric:2.5)
                column(name: "instance_store", value:"4 x 800 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: true)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 39)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "i2.8xlarge")
                column(name: "family", value: "Storage optimized")
                column(name: "ecu", value: "104")
                column(name: "physical_processor", value: "Intel Xeon E5-2670v2")
                column(name: "network_performance", value: "10 Gigabit")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: "Yes")
                column(name: "intel_turbo", value: "Yes")
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 244)
                column(name: "vcpus", valueNumeric: 32)
                column(name: "clock_speed", valueNumeric:2.5)
                column(name: "instance_store", value:"8 x 800 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 40)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "hi1.4xlarge")
                column(name: "family", value: "Storage optimized")
                column(name: "ecu", value: "35")
                column(name: "physical_processor", value: "Intel Xeon Family")
                column(name: "network_performance", value: "10 Gigabit")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 60.5)
                column(name: "vcpus", valueNumeric: 16)
                column(name: "clock_speed", valueNumeric:2.4)
                column(name: "instance_store", value:"2 x 1024 (SSD)")
                column(name: "is_ebs_optimized", valueBoolean: false)
            }
            
            insert(tableName: "flavors") {
                column(name: "id", valueNumeric: 41)
                column(name: "version", valueNumeric: 0)
                column(name: "name", value: "hs1.8xlarge")
                column(name: "family", value: "Storage optimized")
                column(name: "ecu", value: "35")
                column(name: "physical_processor", value: "Intel Xeon E5-2650")
                column(name: "network_performance", value: "10 Gigabit")
                column(name: "processor_architecture", value: "64-bit")
                column(name: "intel_aes_ni", value: "Yes")
                column(name: "intel_avx", value: null)
                column(name: "intel_turbo", value: null)
                column(name: "deleted", valueBoolean: false)
                column(name: "is_disabled", valueBoolean: false)
                column(name: "is_public", valueBoolean: true)
                column(name: "is_ebs_storage", valueBoolean: true)
                column(name: "memory", valueNumeric: 117)
                column(name: "vcpus", valueNumeric: 16)
                column(name: "clock_speed", valueNumeric:2)
                column(name: "instance_store", value:"24 x 1048")
                column(name: "is_ebs_optimized", valueBoolean: false)
            }

        }
}
