//>>built
require({cache:{"url:FogPanel/templates/Pagination.html":'<div class="${theme}" role="presentation" data-dojo-attach-point="containerNode">\r\n    <div class="${_containerClass}" data-dojo-attach-point="containerNode"></div>\r\n</div>'}});
define("FogPanel/Pagination","dojo/_base/declare,dojo/parser,dojo/ready,dojo/Evented,dojo/dom-construct,dojo/i18n!js/dojo-1.8/FogPanel/themes/Pagination/nls/Pagination.js,dojo/on,dojo/query,dojo/text!./templates/Pagination.html,dijit/_TemplatedMixin,dijit/_WidgetBase,dojo/number".split(","),function(f,i,j,e,k,g,l,d,m,n,o,c){e=f("FogPanel.Pagination",[o,n,e],{templateString:m,constructor:function(a,b){this._setPublicDefaults();f.safeMixin(this,a);this._setPrivateDefaults();this.watch("totalResults",
this.render);this.watch("resultsPerPage",this.render);this.watch("currentPage",this.render);this.watch("pagesPerSide",this.render);this.watch("showPreviousNext",this.render);this.watch("showFirstLast",this.render);this.domNode=b},startup:function(){this.domNode?(this.render(),this.loaded=!0,this.emit("load",{})):this.destroy()},postCreate:function(){this._createEventHandlers()},destroy:function(){var a;if(this._eventHandlers)for(a=0;a<this._eventHandlers.length;a++)this._eventHandlers[a].remove();
k.empty(this.domNode);this.inherited(arguments)},render:function(){this._endHTML=this._middleHTML=this._startHTML=this._html="";this._npCount=this._firstMiddle=this._lastMiddle=this._middleCount=0;this._helipText="";this._totalMiddlePages=2*this.pagesPerSide+1;this._helipText=this.helip||"";this.currentResultStart=this.currentPage*this.resultsPerPage;this.currentResultEnd=this.currentResultStart+this.resultsPerPage;if(this.resultsPerPage&&this.totalResults>this.resultsPerPage){this._html+='<ul role="presentation">';
this._currentIndex=this.currentPage?parseInt(this.currentPage,10):1;this._firstPage=1;this._previousPage=this._currentIndex-1;this._nextPage=this._currentIndex+1;this.totalPages=Math.ceil(this.totalResults/this.resultsPerPage);if(this.showPreviousNext)this._npCount=2;this._paginationCount=this._npCount+this._totalMiddlePages;if(this.totalPages===this._paginationCount)this._helipText="";if(this.showPreviousNext){var a=this._itemDisabledClass,b="";if(1<this._currentIndex)a=this._itemEnabledClass,b=
'data-page="'+this._previousPage+'"';this._startHTML+='<li role="button" tabindex="0" title="'+this._i18n.pagination.previousTitle+'" class="'+this._itemClass+" "+this._itemPreviousClass+" "+a+'" '+b+"><div><span>"+this._i18n.pagination.previous+"</span></div></li>"}this.showFirstLast&&(this._currentIndex>this.pagesPerSide+1?this._startHTML+='<li role="button" tabindex="0" class="'+this._itemClass+" "+this._itemFirstClass+" "+this._itemEnabledClass+'" title="'+this._i18n.pagination.firstTitle+'" data-page="'+
this._firstPage+'"><div><span>'+c.format(this._firstPage)+this._helipText+"</span></div></li>":this._middleCount-=1,this._currentIndex<this.totalPages-this.pagesPerSide?this._endHTML+='<li role="button" tabindex="0" class="'+this._itemClass+" "+this._itemLastClass+" "+this._itemEnabledClass+'" title="'+this._i18n.pagination.lastTitle+" ("+c.format(this.totalPages)+')" data-page="'+this.totalPages+'"><div><span>'+this._helipText+c.format(this.totalPages)+"</span></div></li>":this._middleCount-=1);
if(this.showPreviousNext){a=this._itemDisabledClass;b="";if(this._currentIndex<this.totalPages)a=this._itemEnabledClass,b='data-page="'+this._nextPage+'"';this._endHTML+='<li role="button" tabindex="0" title="'+this._i18n.pagination.nextTitle+'" class="'+this._itemClass+" "+this._itemNextClass+" "+a+'" '+b+"><div><span>"+this._i18n.pagination.next+"</span></div></li>"}for(a=1;a<=this.totalPages;a++)if(a<=this._currentIndex+this.pagesPerSide&&a>=this._currentIndex-this.pagesPerSide){if(0===this._firstMiddle)this._firstMiddle=
a;this._middleHTML+=this._createMiddleItem({index:a,currentIndex:this._currentIndex});this._middleCount++;this._lastMiddle=a}if(this._lastMiddle===this.totalPages)for(this._remainderStart=this._firstMiddle-1;this._middleCount<this._totalMiddlePages&&!(this._remainderStart<=this._firstPage);){this._middleHTML=this._createMiddleItem({index:this._remainderStart,currentIndex:this._currentIndex})+this._middleHTML;this._middleCount++;this._remainderStart--}else if(this._firstMiddle===this._firstPage)for(this._remainderStart=
this._lastMiddle+1;this._middleCount<this._totalMiddlePages&&!(this._remainderStart>=this.totalPages);){this._middleHTML+=this._createMiddleItem({index:this._remainderStart,currentIndex:this._currentIndex});this._middleCount++;this._remainderStart++}this._html+=this._startHTML+this._middleHTML+this._endHTML;this._html+="</ul>"}this._html+='<div class="'+this._clearClass+'"></div>';this.containerNode.innerHTML=this._html;d(this.containerNode).removeClass(this._loadingClass);this.disabled=!1;this.emit("render",
{})},_createMiddleItem:function(a){var b=this._itemEnabledClass,h='data-page="'+a.index+'"';if(a.index===a.currentIndex)b=this._selectedClass,h="";return'<li role="button" tabindex="0" title="'+this._i18n.pagination.pageTitle+" "+c.format(a.index)+'" '+h+' class="'+this._itemClass+" "+this._itemMiddleClass+" "+b+'"><div><span>'+c.format(a.index)+"</span></div></li>"},_setPublicDefaults:function(){this.totalResults=0;this.resultsPerPage=10;this.currentPage=0;this.pagesPerSide=2;this.showFirstLast=
this.showPreviousNext=!0;this.helip=g.pagination.helip;this.theme="dojoPage"},_setPrivateDefaults:function(){this._i18n=g;this._eventHandlers=[];this._containerClass="pagDijitContainer";this._loadingClass="pagDijitLoading";this._selectedClass="pagDijitSelected";this._newSelectedClass="pagDijitNewSelected";this._itemClass="pagDijitItem";this._itemEnabledClass="pagDijitItemEnabled";this._itemDisabledClass="pagDijitItemDisabled";this._itemMiddleClass="pagDijitItemMiddle";this._itemFirstClass="pagDijitItemFirst";
this._itemLastClass="pagDijitItemLast";this._itemPreviousClass="pagDijitItemPrevious";this._itemNextClass="pagDijitItemNext";this._clearClass="pagDijitClear"},_createEventHandlers:function(){var a=this;this._eventHandlers.push(l(a.containerNode,"[data-page]:click",function(){if(!a.disabled){a.disabled=!0;d(".pagDijitItem",a.containerNode).removeClass(a._selectedClass);d(this).addClass(a._newSelectedClass);d(a.containerNode).addClass(a._loadingClass);var b=parseInt(dojo.query(this).attr("data-page")[0],
10),c=b*a.resultsPerPage;a.emit("page",{bubbles:!1,cancelable:!1,detail:{selectedPage:b,selectedResultStart:c,selectedResultEnd:c+a.resultsPerPage}})}}))}});j(function(){i.parse()});return e});