define({    
    root : "root",
    greeting : "",
    admin : {
        name : "Admin",
        administrator : "Administrator",
        contactAdmin : "Error contactar admin"
    },   
    common : {
        vCPUCore: "vCPU Core",
        memory: "memoria",
        editOfferTitle : "Editar Informática Oferta",
        free: "libre",
        serviceName:"Service Name",
        itemName:"Item Name",
        changedBy:"Changed By",
        oldCost:"Old Cost",
        newCost:"New Cost",
        changedDate:"Changed Date",
        selectVM : "Seleccione VM",
        selectTier : "Seleccione Tier",        
        noVPCMsg: "Usted no tiene ninguna vpc embargo , cree uno.", 
        noTierMsg : "Usted no tiene ningún nivel de este VPC ! ",
        noVPCandTierMsg : "No hay vpc creado por niveles, crear una VPC continuación, agregue nivel",        
        
        noVPCandLBMsg : "No hay vpc creado por LB público , crear una VPC continuación, agregue LB pública",
        noLBMsgInfo : "Usted no tiene ningún nivel de este VPC !",
        
        noVPCandInternalLBMsg : "No hay nivel creado por libra interno , crear niveles luego añadir libras interna",
        noInternalLBMsgInfo : "Usted no tiene ningún equilibrador de carga interno , sin embargo, por favor adquiera una dirección IP pública a continuación, configurar LB",
        
        noVPCandPublicIPMsg : "",
        noVPCPublicIPMsgInfo : "",
        
        noVPCandVMMsg : "No hay nivel creado para VM , crear niveles luego añadir VM",                 
        noVMListMsg : "Usted no tiene ninguna vm embargo , cree uno.",
        noAcl : "No ACL",
        noStaticMsg: "Por favor Goto Public menú ip, a continuación, seleccione, y permitir statcnat", 
        nopfMessage : "Por favor menú ip pública Goto, a continuación, seleccione IP y configurar portforwarding",
        noVPCAvalilableMsg: "VPC no está disponible en la zona básica", 
        topology: "VPC Topología",
        user:"usuario",
        noZone :  "No Zone",
        noVPC : "No VPC",
        selectNetworkOffer : "Seleccione Oferta de red",
        noTier : "No Nivel",
        selectACL : "seleccione acl",
        staticNat:"Static Nat",
        publicLbIP:"Public LB IP",
        virtualMachine:"Virtual Machine",
        internalLb:"Internal LB",
        privateGateways:"Private Gateways",
        publicIP:"Public IP",
        s2sVpn:"Site-to-Site VPNs",
        portForwardingIP:"Port Forwarding IP",
        networkAcl:"Network ACL",
        router:"Router",
        changeAcl:"Change ACL",
        vpnCustomerGateway : "VPN cliente de Gateway",
        ipsecPresharedKey:"IPsec Preshared-Key",
        details: "Detalles",
        algorithm: "algoritmo",        
        sourcePort: "Puerto de origen",
        instancePort: "Puerto Instancia",
        actions : "Actions",
        vpn: "VPN",
        inactive: "inactivo",
        ruleNo :"Rule Number",
        protocolType : "Tipo de protocolo",
        selectVPC : "Seleccione VPC",
        selectVPNCustomer : "Select VPN Customer Gateway",
        allVPC : "Todos VPC",        
        vpcName : "Nombre VPC",
        aclName : "ACL-Nombre",
        security: "Seguridad",
        tiers : "Tiers",
        tier: "Tier",
        editRule : "Editar regla",
        deleteRule : "eliminar regla",
        networkACL : "Red de ACL",
        cidr : "CIDR",
        backtoDashboard : "Volver a Cloud Service",        
        customerGW: "cliente GW",   
        vpnPrivateGW: "VPN GW privado",   
        vpnConnection: "Conexión VPN",   
        gateway : "Puerta de enlace",
        vpnEnabled : "Red de ACL",
        locked:"está bloqueado",
        lockTime:"Time Lock",
        yes:"Sí",
        intheData : "en el centro de datos",
        publicNw : "Nw Pública",
        publicGateway : "Pasarela Pública",
        vpnGateway : "Pasarela vpn",        
        privateGateway : "Puerta de enlace privado",        
        no:"No",        
        createdDate : "Fecha creacion",
        vpnEnabledError : "No se puede habilitar VPN, póngase en contacto con administrador",
        ivitationMailSucess : "Correo enviado satisfactoriamente a los usuarios",
        resendInvitationSucess: "Invitación enviada con éxito", 
        vpnDisable : "VPN para discapacitados",
        vpnDisableTitle :"Desactivar VPN",
        vpnEnableTitle :"Permitir VPN",        
        invalidEmail:"correo electrónico es inválida",
        emailExist:"Email ya existen",
        duplicateEmail : "email duplicados",
        vpnDisableError : "No se puede deshabilitar VPN, póngase en contacto con administrador.",        
        error: "Error",
        loadBalancer: "Equilibrador de carga",
        addVM: "Añadir VM",
        resend:"Reenviar",
        removeVM: "Retire VM",
        policy:" Política",
        CostPerPolicyPerMonth: "Costo/Política/Mes",
        CostPerRulePerMonth: "Costo/Regla/Mes",
        CostPerConnectionPerMonth: "Costo/Conexión/Mes",         
        rules:" Reglas",        
        portForward: "Port Forwarding",
        comingSoon : "Proximamente",
        notAvailable : "No disponible",
        selectNetwotk:"Seleccione Netwotk",
        bit32 : "32bit",
        average:"Promedio",
        excellent:"Excelente",
        good:"Bueno",
        duplacateEmailMsg: "Correo electrónico debe ser único",
        unit: "Unidad",
        select: "Seleccionar",
        loadBalancing:"Equilibrio de carga",
        portForwarding:"Puerto Reenvío",
        bit64 : "64bit",
        noNetwork:"Sin red",    
        networkType: "Tipo de red",
        supportedService:"Servicio Apoyado",
        networkName:"Nombre de la red",
        network:"Red",
        protocol : "Protocolo",
        defaultVal: "defecto",
        ipAddress :"Dirección IP",
        computingOffers: "computar las ofertas",
        diskOffers : "Ofertas de disco",
        templates: "plantillas",
        bandwidthMiscInfo:"Ancho de banda de información miscelánea",
        snapshotMiscInfo:"Snapshot información miscelánea",       
        vmSnapshotMiscInfo:"VM Snapshot información miscelánea",      
        networkOffer :"Oferta de red",
        ipMiscInfo:"Ancho de banda de información miscelánea",        
        prepaidPaymentMessage:"Realizar pago para continuar!",
        hypervisor:"Hypervisor",
        CostPerGBPerMonth : "Costo/GB/Month",
        zoneCostInvalidMsg : "No puede ser NulL",
        exceedBandwidthCost : "Exceso de ancho de banda Costo/GB/Mes",
        vmRunningCostPerMonth : "VM Prendidas Costo/Mes",
        vmStopageCostPerMonth : "Vm Apagadas Costo/Mes",            
        setupCost : "Costo Configuracion",            
        runningCostPerHr : "VM Prendidas Costo/HR",            
        stopageCostPerHr : "VM Apagadas Costo/HR",    
        perGBPerHr : "Por GB/Hora",
        oneTime: "Unico",
        storageCostPerMonth : "Costo Almacenamiento/Mes",            
        strong : "Fuerte",
        selectNic: "seleccionar Nic",
        allocated: "Asignado",
        falseData : "Falso",
        vcpus: "VUPCs",
        setasDefault: "Establecer como predeterminado",
        medium : "Medio", 
        custom : "Personalizado",
        disable : "Deshabilitado",
        enabled : "Habilitado",
        disabled : "Deshabilitado",            
        enable : "Habilitado",
        manual: "manual",
        zone : "Zona",
        pod : "Pod",
        noNetworkOffer:"Sin Oferta de Red",
        selectOS : "Seleccionar OS",
        selectCategory : "Seleccionar categoria",            
        cluster : "Cluster",            
        allZone : "Todas las Zonas",
        allPod : "Todos los Pod",
        CostPerIPPerMonth : "Costo/IP/Mes",
        allCluster : "Todos los Cluster",            
        host : "Host",
        weak : "Debil",
        displayName : "Display Name",
        idCaps : "ID",
        email : "Correo",
        gbPerMonth : "/GB/mes",
        countSummary : "Contar Resumen",
        gbPerHr : "/GB/Hr",
        amount : "Monto",
        type:"Tipo",       
        netmask:"Máscara de red",
        taxAmount : "Monto impuesto",
        level : "Nivel",
        allPlan:"Todos los Planes",
        allUser:"Todos los usuarios",
        state : "Estado",
        name: "Nombre",
        bottom : "Fondo",
        open: "Abierto",
        close : "Cerrado",
        active:"ACTIVO",
        selectReply:"Selecionar respuesta",
        inProgress:"En progreso",
        closed : "Cerrado",
        staff : "Personal",
        ips:"IPs",
        client : "Cliente",
        clients : "Clients",            
        onHold : "En Espera",
        description : "Descripcion",
        baseOSName : "OS Base",
        operatinSystem : "Sistema Operativo",
        gb: "GB",
        privatePort :"Puerto Privado",
        publicPort :"Puerto Publico",
        vmList :"Lista VMs",
        vm:"VM",
        enableStaticNat:"Habilitar NAT estatico",
        disableStaticNat:"Deshabilitar NAT estatico",
        core: "Core",            
        mb: "MB",
        MBs : "MB/s",
        month : "Mes",  
        hour : "Hora",
        billingCostPeGBHR : "(Costo de facturacion)Por GB/por HR",
        cost : "Costo",
        unitCost : "CostoUnidad",
        runningCost : "Costo andante",            
        cpu : "CPU", 
        speed : "Velocidad",
        mhz: "MHz",
        date : "Fecha",
        deleteData : "Borrar",
        startDate:"Fecha de Inicio",
        endDate:"Fecha de cierre",
        maxUses:"Usos Maximos",
        promotionValue:"Valor Promocion",
        value:"Valor",
        uses:"Usos",
        promotionType:"Tipo",
        notes:"Notas",
        code:"Codigo",
        reset : "reajustar",
        action : "Accion",            
        all : "Todos",
        empty : "Vacio",
        event : "Evento",
        dd : "DD",
        mm : "MM",
        yyyy : "YYYY",     
        view : "Ver",
        viewed : "Visto",
        trialLimit : "Limite Trials",
        mbOfMemory : "MB de Memoria",
        amountSummary : "Resumen Monto",
        edit:"Editar",
        downloadPDF : "Descargar pdf",
        viewInvoice : "Ver Factura",
        primaryStorage : "Almacenamiento primario",
        resetPassword:"Cambiar Password",
        showApiKey:"Ver API Keys",
        resetApiKey:"Cambiar API Keys",
        revokeApiKey:"Revocar Acceso API ",
        grantApiKey:"Permitir Acceso API ",
        noDepartment:"Sin Departamento",
        vpc: {
            name: "VPC",
            yourVpc : "Su VPC",
            vpcs : "VPC de",
            tiers:"En tercer lugar",
            instance: "Instancia",            
            publicLB : "LB Pública",
            internalLB :"LB interna",
            publicIPAdd : "IP pública Agregar",  
            publicIP : "IP pública",                  
            staticNat : "estática Nat"
        },
        menu : {
             home: "Inicio",
              cloud: "Nube",
              instance: "Instancia",
              storage: "Almacenamiento",
              snapShot: "SnapShot",
              firewall: "Firewall",
              network: "Red",
              health: "Salud",
              services : "Servicios",
              sshKey : "SSH clave",
              bandwidth : "Ancho de Banda",
              ipManager : "Administrador IP ",
              templates : "Templates",
              billing : "Facturacion",
              currentUsage : "Uso Actual",
              invoice : "Factura",
              payments : "Pagos",
              recurringItems : "Items Recurrentes",
              support : "Soporte",
              Stats : "Estadisticas",
              billableItem : "Item Facturable",
              paymentReport : "Reporte de Pagos",
              activity : "Actividad ",
              events : "Eventos",
              alerts : "Alertas",
              notifications : "Notificaciones",
              limitSummary:"Limit Summary"
        },
        apiMessage :{
            resetKey:"Cambio Exitoso de API Key !",
            revokeKey:"Revocacion exitosa de API Key!",
            grantKey:"Permitir API Key exitoso !"
        },
        exceptionMsg : {
            validationException : "ExcepcionValidacion",
            cardVerificationFailed : "Verificacion de Tarjeta Fallida",
            unabletoVerifyCard : "Imposible verificar tarjeta,  Intente de Nuevo",
            unabletoCreateAccount : "Imposible crear cuenta, Intente de nuevo o contacte a su administrador"            
        },
        cloudStack : {
            errorMessage : "Imposible procesar su requerimiento contacte a su administrador"
        },
        password:{
            notMatch : "Password no considen",
            lengthConstrain : "Password debe ser minimo de 8 caracteres y maximo de 15",
            tooShort:"Demasiado corto",
            strong:"Fuerte",
            medium:"Medio",
            weak:"Debil",
            resetVMPassword : "Cambiar password VM"
        },
        username:{
            valid:"Nombre de Usuario ya existe",
            exists:"Nombre de Usuario ya existe",
            inValid:"Nombre de usuario invalido o de longitud incorrecta"
        },
        account : {
            name : "Cuenta",
            accountType : "Tipo de Cuenta",
            exceededBy : "Excedido por",
            selectCountry :"Escoger Pais",
            selectState : "Seleccionar Estado",
            passworResetSuccess : "Password cambiado con exito",
            oldPasswordNotMatch : "Password antiguo no coincide",
            passwordNotMatch : "Password no coincide",
            passwordShouldEmpty : "Debe especificar el Password ",
            passwordLengthConstrain : "Longitud del password debe ser minimo de 8 caracteres y maximo de 15",
            mailSentSucessMessage : "Correo enviado con exito , Ingrese a su correo para cambiar el password",
            mailSentSucessActivationMessage : "Correo enviado con exito, Ingrese a su correo para activar su cuenta",
            accountCancelled : "Cuenta cancelada!",
            accountCancelError : "No se puede cancelar cuenta!",    
            accountEnabled : "Cuenta Habilitada!",
            accountEnabledError : "No se puede habilitar cuenta!",
            accountDisabled : "Cuenta Deshabilitada!",
            accountDisabledError : "No se puede habilitar cuenta!",
            accountSuspended: "Cuenta Suspendida!",
            accountSuspendError: "No se puede suspender Cuenta!",     
            amountRefunded:"Monto Reembolsado!",
            amountRefundError:"No se puede Reembolsar Monto!",
            accountLocked : "Cuenta Bloqueada!",
            accountLockError : "No se puede Bloquear Cuenta!",         
            accountUnlocked : "Cuenta Desbloqueada!",         
            accountUnlockedError : "No se puede Desbloquear Cuenta!",         
            resetPasswordSucess : "Cambio de password exitoso!",
            resetPasswordError : "No se puede cambiar password",
            type : {
                RETAIL : "RETAIL",
                TRIAL : "TRIAL"                       
            },
            status : {
                ACTIVE : "ACTIVO",
                BLOCKED : "BLOQUEADO",
                LOCKED : "CERRADO",
                DISABLED : "DESHABILITADO",
                NOT_VERIFIED : "SIN_VERIFICAR",
                SUSPENDED : "SUSPENDIDA",
                CANCELED:"CANCELADO",
                CLOSED : "CERRADO",                    
                active : "Activo",
                blocked : "Bloqueado",
                locked : "Con llave",
                Disabled : "Deshabilitado",
                NotVerified : "No verificado",
                suspended : "Suspendido",
                canceled : "Cancelado",
                closed : "Cerrado",
                verified : "Verificado",
                notVerified : "No verificado"
            }
        },
        baseOS : {
            linux : "Linux",
            windows : "Windows"
        },
        size : {
            sizeName : "common.size.sizeName",
            minSize : "common.size.minSize",
            maxSize : "common.size.maxSize"
        },
        status : {
            ready : "Listo",
            name:"Estatus"
        },
        ip : {    
            name : "IP",
            invalidAcquireIpMessage : "No se puede adquirir IP! Contactar al admistrador",
            acquireIp : "Ip Adquirida",
            acquire : "Adquirir",                
            revoke: "Revocar",
            releaseIP : "Soltar IP",
            cannotReleaseIP : "No se puede soltar IP! Contactar IP",
            noSecondaryIP : "Ip secundarias no disponibles! ",
            userDidntAquireIP : "Usuario no adquiere ningún IP aún"
        },
        message : {
            createStaticRoute:"Added Static route successfully",
            deleteStaticRoute:"Deleted Static route successfully",
            createVPCGateway:"Agregado VPC puerta de entrada privada con éxito",
            privateGatewayDelete:"Deleted Private gateway successfully",
            createVPNConnection:"Added VPN Connection successfully",
            deleteVPNConnection:"Deleted VPN Connection successfully",
            restartVPNConnection:"Restarted VPN Connection successfully",
            createS2SCustomerGateway:"Alta VPN Portal del cliente con éxito",
            deleteS2SCustomerGateway:"Suprimido VPN Portal del cliente con éxito",
            updateS2SCustomerGateway:"Actualizado VPN Portal del cliente con éxito",
            addS2SvpnSuccess:"Creado sitio a sitio VPN con éxito",
            deleteS2SvpnSuccess:"Sitio eliminado de vpn con éxito",
            networkAclRuleDeleted : "Regla eliminado correctamente",
            aclRuleUpdatedSuccess : "Regla actualizado correctamente",
            aclChanged:"ACL Actualizado con éxito",
            tierEdidtedSuccess:"Nivel actualizado correctamente",
            selectTier:"Seleccione Nivel",
            releaseVpcIPSuccess : "Dirección IP eliminado de este VPC éxito",
            addIpToVpcSuccess : "Dirección IP agregada a este VPC éxito",
            vpcCreated:"VPC creado con éxito",
            networkAclCreated:"Red ACL creado con éxito",
            tierCreate:"Nivel creado con éxito",
            internalLBCreate:"InternalLB creado con éxito",
            internalLBDeleted:"InternalLB Eliminado con éxito",
            tierDeleted:"Nivel eliminado correctamente",
            tierRestartSuccess:"Nivel reiniciado correctamente",
            networkAclDeleted:"Red ACL Eliminado con éxito",
            vpcUpdateSuccess:"VPC Actualizado correctamente",
            aclRuleCreated:"Regla ACL creado con éxito",
            vpcDeleted:"VPC Eliminado con éxito",
            vpcRestartSuccess:"VPC reiniciado correctamente",
            invitationSuccess:"Correo Invitación enviada con éxito",
            vpnUserSucess : "Nuevo usuario creado para este vpn",
            vpnUserFailed : "No se puede crear el usuario de esta cuenta, por favor póngase en contacto con administrador",       
            vpndeleteUserSuccess : "Usuario VPN eliminado correctamente",
            vpndeleteUserError:"No se puede eliminar este usuario vpn, por favor póngase en contacto con administrador",
            vpnEnalbed : "VPN habilitado para esta IP",
            vpnEnalbedError : "No se puede Habilitado VPN a esta IP",
            vpnDisabled : "VPN Disabled para esta IP",
            vpnDisabledError : "VPN no puede Disabled para esta IP",   
            networkCreate: "Red Creada exitosamente",
            allVMAddedToLB : "Todos los disponibles Instancia se añaden a esta LoadBalancer",
            noVMAddedToLB : "No VM disponible para este LoadBalancer para eliminar",
            nicCreated:"Nic Creada Exitosamente",
            nicDeleted:"Nic Borrada Exitosamente",
            pullPlanSuccess:"Todos los palnes de ACS exitosamente tranferidos a fogpanel",
            pullTemplateSuccess:"Todas las plantillas se tiran de CloudStack",
            setDefaultNicsuccess:"Determinar Nic predefinido exitosamente VM",
            nicfailed : "No se puede crear NIC contacte al admnistrador",                
            networkUpdated: "Red actualizada exitosamente",
            networkDelete:"Red borrada exitosamente",
            selectIp:"Seleccionar IP",
            enableStaticNatSuccess:"NAT Estatica Habilitada exitosamente ",
            disableStaticNatSuccess:"NAT Estatica Deshabilitada Exitosamente ",
            addPortForwardingRuleSuccess:"Regla de Port Forwarding añadida Exitosamente",
            selectVM:"Seleccione VM.",
            ruleUpdateSuccess:"Regla Actualizada Exitosamente",
            addLoadBalancerRuleSuccess:"Load Balancer añadido Exitosamente",
            addAdditionalVMToLoadBalancerRuleSuccess:"VM añade a esta política con éxito",
            removeVMFromLoadBalancerRuleSuccess:"VM elimina de esta política con éxito",
            addFirewallRuleSuccess:"Firewall añadido exitosamente a esta IP",
            addIpToNetworkSuccess:"IP Añadida exitosamente a esta IP",
            networkHasFirstIPMessage:"Ya adquirio una IP gratis, Crear una VM apara adquirir otra IP",
            releaseIPSuccess:"IP suelta exitosamente para esta red",
            selectHypervisor:"Escoger  Hypervisor",
            noHypervisor:"Sin Hypervisor",
            noCode : "Sin code",
            added : "Añadido",
            created : "Creado !",
            createdError : "Fallo al crear Template!",                
            noTag : "Sin Tag",
            connecting : "Conectando...",
            excesBandwidthCostMsg : "Exceso de ancho de Banda Costo/GB/Mes",
            oneTimeChargeTemp : "Template de cargo unico de tener costo!",
            oneTimeChargeTemplate : "De cargo  unico template!",    
            vmExistMsg : "VMs disponibles con esta oferta de computo.",
            volumeExist : "volumes disponibles con esta oferta de disco.",
            successfully : "Exitosamente",
            addedSuccess : "Añadido Exitosamente!",
            updatedSuccess : "Actualizado Exitosamente!",    
            templUpdated : "Template Actualizado!",
            updatedError : "No se puede actualizar!",                   
            departmentAdded:"Departamento Añadido!",
            noPreDefinetReply:"Sin Respuesta pre-definida",
            addEgressRuleSuccess:"Regla de salida añadida exitosamente",
            cloudStackError:"No se puede realizar esta accion. Contacte a soporte",
            itemAdded : "Item Añadido",
            ItemDeleted : "Item Borrado",  
            ItemUpdated : "Item Actualizado",                 
            ItemUpdateError : "No se puede actualizar este Item",                     
            cannotDelete : "No se puede Borrar!",
            enterContent : "Ingrese Contenido!",
            cannotBeAdded : "No se puede añadir!",
            configMissing : "Config no existe!",  
            deletedSuccess : "Borrado Exitoso",
            trialAccountResource : "Trial Account Resource limit reached!",
            updateSuccess: "Actualizado con exito",
            deletedJobSuccess : "Trabajo borrado con exito",
            failed: "Fallido",
            inProgress : "En Progreso",  
            success: "Exitoso!",
            refreshPage : "Refresque Pagina",
            noDisk:"Sin Disco",
            selectPlan : "Seleccionar Plan",  
            noPlan: "Sin Plan",
            failedContactAdmin : "Fallido! Contactar al administrador",
            contactAdmin : "Contactar al Administrador.",
            resetPassworSuccess : "Cambio de password Exitoso",
            selectOffer : "Seleccionar oferta",
            selectComputingOffer : "Escoja oferta de computo",
            selectTemplate : "Escoger Template",
            selectFirewall : "Escoger Firewall",
            selectNetwork: "Escoger Red",
            selectZone : "Escoger Zona",
            selectPode : "Escoger Pod",
            selectCluster : "Escoger Cluster",  
            selectTag : "Escoger Tag", 
            hostTag : "Host Tag",                 
            selectDiskOffer : "Escoger oferta de disco",
            selectDisk : "Escoger Disk",          
            selectInstance : "Escoger Vm",                          
            noThanks : "No Gracias",
            noTemplate : "Sin Template",
            noFirewall: "Sin Firewall",
            addTemplateError : "No se puede añadir Template",
            addTemplateSuccess : "Template Creado",
            usedBandwidth : "Ancho de banda usado(GB)",
            excedded : "Excedido (GB)",
            totalBandwidth : "Ancho de banda total",
            addInvoiceItem:"No se puede añadir item! Sin borrador de factura",
            itemDeleted:"Item Borrado",                
            noHostAvailable : "Ningun Host disponible para migrar",
            confirmMigratVM : "Confirme que desea migrar esta VM a otro host",
            confirmAnotherMigratVM : "Confirme que desea migrar esta VM a otro almacenamiento primario",
            cannotMigrateInstance : "No se puede migrar VM!",
            vmMigratSucess : "Migracion de VM exitosa",                
            discountDisableInfo:"Descuento deshabilitado para VM mensuales",
            discountErrorInfo:"Todas las cuentas añadidas en esta fecha de inicio y fin",
            cloudStackConfigMissing:"Configuracion no existente!",
            noVMSnapforTrial:"Opcion no disponible para cuentas Trial"
        },
        instance : {
            vmStartedSuccessMessage: "VM Comienza con éxito",
            vmStoppedSuccessMessage : "VM stoped con éxito",
            vmRestartSuccessMessage : "VM reiniciado correctamente",     
            createVM : "Crear VM",
            instanceIP : "IP VM",
            name : "VM",
            vmName : "Nombre VM ",
            selectInstance : "Escoja VM",
            creatingInstance : "Creando VM por favor espere",
            vmError : "No se puede crear Vm contacte al administrador",
            created : "VM Creada",
            startVMError : "No se pude iniciar VM!",
            vmStarted : "VM Iniciada",
            vmStopped : "VM Apagada",                
            stopVMError : "No se puede apagar VM !",
            deleteVMError : "No se puede borrar VM!",
            vmDeleted : "VM Borrada",
            rebootVMError : "No se puede reiniciar VM!",
            vmRebooted : "Reinicio de VM Exitoso ",
            restoreVMSucess : "se ha restablecido",            
            resetVMError : "No puede restablecer Instancia!",  
            resetVMSucess : "VM resetea con éxito",      
            restoreVMError : "No se puede Formatear VM !",
            selectDVDDrive : "Escoja DVD Drive",
            connotAttachIso : "No se puede adjuntar ISO",
            volumeCountReachedTrial: "Numero limite de Volumenes alacanzado!",
            volumeCountReachedVm: "Numero limite de Volumenes alacanzado para esta VM",
            isoAttached : "ISO Adjuntada",
            isoAttachedError : "No se puede adjuntar  ISO",
            isoDettachedError : "No se puede desadjuntar ISO",
            isoDettached : "ISO Desadjuntada",     
            cannotAddVolume : "No se puede añadir Volumen",
            vmNameChanged : "Nombre dysplay a sido cambiado",
            mbOfMemory : "MB de memoria",
            planChanged : "Plan Cambiado",
            planChangedError : "Cambio de plan fallido! Contactar al adminitrador",     
            noSSHKey : "No SSh Key! Cree Key Para cambiar la  key Default ",
            sshKeyChanged : "SSH Key Cambiada",
            startConsole : "Iniciar Consola",
            status : {
                running : "Prendida",
                stopped : "Apagada",
                destroyed : "Destruida",
                starting : "Iniciando",
                stopping : "Apagando",
                exbunging : "Destruyendo" 
            }
        },
        template : {
            centOS : "CentOS",
            debian : "Debian",
            oracle : "Oracle",
            redHat : "RedHat",
            SUSE   : "SUSE",
            windows: "Windows",
            novel  : "Novel",
            unix   : "Unix",
            ubuntu : "Ubuntu",
            name: "Template",
            noTemplate : "No Templates",
            noLinuxTemplate : "Ningun template Linux encontrado ",
            noWindowsTemplate : "Ningun template Windows encontrado ",    
            deleteTemplateError : "No se puede borrar Template!",
            deleteTemplateSuccess : "template Borrado",
            copyTemplate : "Copiar Template",
            noAppTemplateFound : "",
            deleteTempFailed : "Fallo al borrar este Template",
            deleteTempSuccess : "Template borrado exitosamente", 
            grid : {
                templateName : "Nombre Template ",
                operationSystem : "Sistema Operativo",
                osType : "Tipo de OS ",
                zone : "Zona",
                cost : "Costo"                                     
            }
        },
        firewall : {
            name : "Firewall",
            noOutboudData : "No hay datos de salida",
            firewallSuccess : "Firewall Añadido exitosamente!",
            firewallError : "No se puede añadir Firewall!",
            DeletedSuccess : "Borrado exitosamente",                
            firewallLoading : "Firewall Cargando! Espere ",
            noInboundRule : "No tiene reglas de ingreso aun, Cree una",
            noOutboundRule : "No tiene reglas de egreso aun, Cree una",                
            inboundLoading : "De entrada Cargando! Espere",
            outboundLoading : "De salida Cargando! Espere",                
            managePort : "Puerto de Manejeo",
            invalidCIDR : "CIDR Invalido",
            addEgressError : "No se puede añadir Ingreso!",
            protocol : "Protocolo",
            startPort : "Puerto de inicio",
            startPortOrICMPType : "Puerto de inicio/Tipo Icmp ",
            endPortOrICMPCode : "Puerto de inicio/Codigo Icmp ",                
            endPort : "Puerto Final",
            cidr : "CIDR",
            ruleDeleteSuccess : "Regla borrada exitosamente",
            ruleDeleteError : "No se puede borrar esta regla!",
            outboundAddError : "No se puede añadir de salida!",
            outboundAddSuccess : "Regla de salida añadida exitosamente!",                
            inboundAddError : "No se puede añadir de entrada!",
            inboundAddSuccess : "Regla de entrada añadida exitosamente!",                
            noInbound : "No hay datos de entrada",                
            networkUnreachable : "Red inalcanzable",
            hostUnreachable : "Host inalcanzable",
            protocolUnreachable : "Protocol inalcanzable",
            portUnreachable : "Port inalcanzable",
            fragmentationNeeded : "Se necesita fragmentacion y ningun fragmento fue especificado",
            sourceRouteFailed : "Ruta fuente fallida",
            designationNetworkUnknown : "Red desiganada desconozida",
            designationHostUnknown : "Host designado desconocido",
            sourceHostIsolated : "Host fuente Aislado",
            networkAdministrativelyProhibited : "Red prohibida por la administracion",
            hostAdministrativelyProhibited : "Host prohibido por la administracion",
            networkUnreachableForTos : "Red inalcanzable para Tos",
            hostUnreachableForTos : "Host inalcanzable para Tos",                   
            datagramForNetwork : "Datagram Para la Red",    
            datagramForHost : "Datagram Para el Host",    
            datagramForTosAndNetwork : "Datagram Para tos & Red",    
            datagramForTosAndHost : "Datagram for tos & Host",                
            ttlExpiredTransit : "TTL Transito expirado",
            fragmentationReassenblyExceeded : "Fragmentation reassenbly exceed",                
            pointerIndicatesError : "Pointer indicates the error",
            missingRequiredOption : "missing a required option",
            badLength : "Mala longitutd",
            icmpType : "ICMP Tipo",
            icmpCode : "ICMP Codigo",
            trafficType: "Tipo de tráfico"
        },
        ticket : {
            ticketId : "Id Ticket  ",
            tockenNo : "Token.No",
            subject : "Asunto",
            department : "Departamento",
            priority : "Prioridad",
            low: "Baja",
            high : "Alta",
            normal : "Normal",
            postedDate: "Fecha de ingreso",
            ticketClosed : "Ticket Cerrado!",
            ticketAdded : "Ticket Añadido!",
            addTicketError : "No se puede Añadir ticket!"          
        },
        report : {                                    
            toDate: "Fechas Hasta",
            fromDate : "Fecha Desde",
            forDateRange : "Rango de Fechas",           
            forAccount : "Para cuenta",
            forZone : "Para Zona",
            billableItemList : "Lista de item",
            forBillableItem : "Para Item facturables",                       
            plan : "plan de",                
            nonZoneBased : "No Basado en zona",
            zoneBased : "Basado en Zona",
            selectBillableItem : "Seleccione Item Facturable!"
        },
        options : {          
            allZone    : "Todas las Zonas",
            selectZone : "Seleccionar zona",
            nonZone : "Sin Zona"
        },
        alerts : {
            alertLoading : "Alertas cargando! Espere",
            eventLoading : "Eventos cargado! Espere",
            notificationLoader : "Notificaciones Cargando! Espere",
            grid : {
                layout : {        
                    ip : "IP",
                    timeAddrerss : "Direccion Tiempo",
                    attempt : "Intento",
                    attemptFail : "Intento Fallido",
                    attemptSuccess : "Intento Exitoso"
                }
            }
        },
        loader : {
            imageLoadError : "No se puede cargar imagen",
            loading : "Cargando",
            jobLoading : "Cargando Trabajos",
            loadingPleaseWait : "Cargando Por favor espere...",
            templateLoader : "Template Cargando! Espere"
        },
        billing: {
            paid : "Pagado",
            invoiceLoader : "Factura Cargando! Espere",
            paymentLoader : "Pagos cargando! Espere",
            createVMToPayment : "Crear una VM y hacer pagos",
            paymentSuccess : "Pago realizado exitosamente!",
            paymentFailed : "Pago fallido",
            cardAdded : "Tarjeta Añadida!",
            taxName:"Nombre de Impuesto",
            taxPercent : "Porcentaje de Impuesto",
            currentDue : "Deuda actual",
            billingCycle : "Ciclo de Facturacion",
            noOfUses : "No. De usos",
            cardNotVerified : "Tarjeta no verificada!",
            customItem : "Item personalizado",
            recurringItem : "Item Recurrente",    
            taxPercentage : "Porcentaje de Impuesto ",
            processingFee : "Tarifa de procesamiento",
            grid : {
                layout : {                                                                                
                    invoiceNo : "No de Factura",
                    previousBalance : "Balance Previo",
                    payments : "Pagos",
                    currentUsage : "Uso actual",
                    totalPayable : "Total a pagar",
                    previousInvoiceDate : "Fecha de factura anterior",
                    invoiceDate : "Fecha de factura",                        
                    tokenNo :"Token No.",
                    paymentDate :"Fecha de pago",
                    amount :"Monto",
                    processingFee :"Tarifa de procesamiento",
                    totalAmount :"Monto total",
                    tockenNo:"Tocken No"
                }
            }
        }
    },
    user : {
       userID : "Id de Usuario",
        userName : "Nombre de usuario",
        SSHKey : {
            SSHKeyDeleted : "SSH key Borrada!",
            SSHKeyDeletedError : "No se puede borrar  SSH Key! Contactar usuario",
            fingerPrint : "Huella dactilar",
            sshKeyCreated: "SSH key Creada",
            cannotCreateSSHKey : "NO se puede crear  SSH Key! Contactar administrador"
        },
        instance : {
            createInstance : "Crear VM"  
        },
        loader : {
            instanceLoader: "VM cargando! Espere",
            volumeLoading : "Volumen Cargando",
            snapshotLoading : "Snapshot Cargando! Espere...",
            creatingVolume :  "Creando Volumen"
        },
        snapshot : {
            createSnapshot : "Crear Snapshot",
            snapshotSuccess : "Snapshot Exitosa",
            snapshotMessage : "Puede actualizar/Borrar snaphots programados actualmente.",
            snapshotError : "No se puede tomar snapshot",  
            created : "Snapshot Creado",
            backedup : "Respaldado Up",
            snapshotUpdateSuccess : "Configuracion snapshot actualizada exitosamente ",
            snapshotUpdateError :"No se puede actualizar configuracion de snapshot ",
            deleteSnapshotFailed : "Fallo al borrar snapshot",
            volumeSnapshotMessage : "Haga click en el Volumen que quiere sacar un snapshot.",
            volumeAutoSnapshotMessage : "Haga click en el Volumen que quiere sacar un snapshot periodico",
            vmSnapshot : {
                vmSnapshotLoading : "Snaoshot de VM cargando! Espere",
                cannotRevertVM : "No se puede revertir snapshot de VM! Contactar administrador",
                revertVMSuccess : "VM snapshot revertida exitosamente",
                cannotDeleteVMSnapsot : "No se puede borrar  VM Snapshot! Contacte al administrador",
                vmSnapshotDeletedSuccess : "VM snapshot borrada exitosamente",
                cannotCreateVmSnapshot : "No se puede crear VM Snapshot! Contacte al Administrador",
                vmSnapshotCreated : "VM snapshot Creado exitosamente",
                vmSnapshotNotAvailable : "VM Snapshot No disponible para cuentas trial",
                resizeVolume : "Cambiar tamaño del Volumen"
            }
        },
        storage : {
             name: "Almacenamiento",
            addedStorage : "Añadir Almacenamiento",
            addVolumeError : "No se puede añadir Volumen",
            createdAndAttached : "Volumen creado y adjuntado a VM exitosamente.",
            cannotDetached : "No se puede desadjuntar",
            volumeLimitReached: "Limite de volumenes alcanzado!",
            notAttached : "No adjuntado",
            detachMessage : "Desadjunte este volumen de la VM",
            cannotAttached : "No se puede Desadjuntar",      
            volumeDeleted : "No se puede Borrar",
            volumeAttachedError : "Adjuntar volumen Fallido",       
            volumeDetachedFailed : "Fallo al desajuntar volumen ,La VM no permitio desadjuntar el dispositivo",       
            deleteVolumeError : "No se puede borrar el Volumen",
            storageDetached : "Almacenamiento desadjuntado",
            volumeAttached : "Volumen adjuntado",
            resizeError : "No se puede cambiar el tamaño del almacenamiento",
            upgradeSuccess : "Almacenamiento aumentado exitosamente",
            upgradeVolumeError : "No se puede aumentar el disco con este plan",
            createVMAddVolume : "Crear una VM y añadir un Volumen"
        },        
        grid : {
            instance : {
                noInstance : "Sin VM",
                layout : {
                    vmName : "Nombre de la VM",
                    plane  : "Plan",
                    ip     : "IP",
                    zone   : "Zona",
                    status : "Estatus",
                    action : "Accion"                       
                }
            },
            storage : {
                noVolume : "No tiene volumenes aun. Cree uno ahora.",
                layout : {
                    diskName : "Nombre de disco",
                    plan : "Plan",
                    instanceAttached : "VM adjuntada",
                    size : "Tamaño(GB)",
                    status : "Estatus",
                    action : "Accion"
                }
            },
            snapshot : {
                noSnapshot : "No hay  Snapshot",
                layout : {
                    snapshotName : "Nombre Snapshot",
                    volumeName : "Nombre Volumen ",
                    instanceName : "Nombre VM",
                    type : "Tipo",
                    createdDate : "Fecha creacion",
                    status : "Estatus",
                    action : "Accion",
                    parentName : "Padre",
                    isCurrent : "isCurrent"
                },
                autoSnapshot : {
                    layout : {
                        time : "Hora",
                        schedule : "Horario",
                        timeZone : "Zona Horaria",
                        keep : "Mantener",
                        action : "Accion",
                        name : "Nombre",
                        diskName : "Nombre del Disco",
                        type : "Tipo",
                        volumeType : "Tipo del Volumen",
                        snapshotConfig : "Configuracion del Snapshot"
                    }
                }
            }  
        }
    }
});
