<p>This End User Agreement ("<strong>Agreement</strong>") is a <strong>binding legal document</strong> between AssistanZ and you, which explains your rights and obligations as an End User of FogPanel, a product of AssistanZ. <strong>"End User"</strong> means either (a) you as an individual or (b) your company, if you are using FogPanel in your capacity as an employee or agent of a company. You identify the specific "End User" during the registration process. <strong>"AssistanZ"</strong> means AssistanZ Networks Pvt. Ltd.(Reg. No: U72200TZ2005PTCO11884) 1136 Jayyseeli Plazaa, Dr.Radhakrishnan road, Gandhipuram, Coimbatore, Tamil Nadu, India - 641012.</p>
<p>By allowing the "I Agree to the terms and conditions of the End User Agreement" box to remain checked, or by installing or using FogPanel, <strong><u>End User agrees to be bound by this Agreement</u></strong>. If you do not agree to this Agreement, then uncheck the "I Accept" box and do not install or use FogPanel. This agreement does not apply to the "EndUser", who are granted by AssistanZ based on exclusive usage agreement.</p>
<p>The "Agreement" also includes any AssistanZ policies or documents referenced in this document, including AssistanZ's Privacy Policy at <a target="_blank" href="http://www.fogpanel.com/policies/privacy">http://www.assistanz.com/privacy</a>.</p>
<p>From time to time, AssistanZ may modify this Agreement, including any referenced policies and other documents. Any modified version will be effective at the time it is posted. To keep abreast of your license rights and relevant restrictions, please bookmark this Agreement and read it periodically. By using FogPanel after any modifications, End User agrees to all of the modifications.</p>

<h3>1. Introduction to FogPanel and License Terms.</h3>
<p><strong>1.1 What's Included in "Software".</strong> AssistanZ offers many different software products for download, including FogPanel and others. <strong>"Software"</strong> here means FogPanel that End User orders from AssistanZ and downloads from FogPanel website. The term also includes (a) related documentation, (b) any Updates (defined below) to the Software. To be clear, any add-ons, plug-ins, APIs or other code offered by third parties or created by End User itself are not "Software", and AssistanZ is not responsible for and does not offer any warranty, indemnity or support for those items.</p>
<p><strong>1.2 The "FogPanel".</strong> This Agreement uses <strong>"FogPanel"</strong> to refer to the Software and its updates.</p>
 
<p><strong>1.3 AssistanZ's Maintenance Offerings.</strong> For additional fees, AssistanZ offers <strong>"Maintenance"</strong> to End Users as described at <a href="http://fogpanel.com/support/offer" target="_blank">http://fogpanel.com/support</a>. Maintenance includes (1) any generally released updates, upgrades, patches and bug fixes for the Software (<strong>"Updates"</strong>) when and if generally released at <strong>AssistanZ's</strong> sole discretion, (2) web-based support and phone support (depending on End User's support level) as described in the link above, and (3) other support features as described in the link above.</p>
 
<p><strong>1.4 Limits on Authorized Resources.</strong> When buying a license to the Software, End User pays the fees for a specific number of resources, which are counted based on number of hypervisors used for virtual machine creation (“Authorized Resources”).</p>

<h3>2. License to Use <strong>AssistanZ</strong> Software</h3>
<p><strong>2.1 Software, Generally. AssistanZ</strong> grants End User a worldwide, non-exclusive, non-transferable, non-sublicense-able right to use the Software, subject to the terms and conditions of this Agreement. Software licenses are perpetual unless terminated as described in this Agreement. Only Authorized Users may use the Software, and only up to the permitted product usage limit. All use of Software must be in accordance with the relevant <strong>AssistanZ</strong> documentation and policies. End User may make a limited number of copies of the Software as is strictly necessary for purposes of data protection, archiving, backup. Unless <strong>AssistanZ</strong> agrees otherwise in writing, End User may only install, use or make available the Software on End User's hardware systems, whether owned, leased or controlled. End User will be responsible for any use of the Software on any hardware systems not owned, leased or controlled by End User (<strong>"Uncontrolled Systems"</strong>).</p>
 
<p><strong>2.2 Updates and Supplementary Software.</strong> The terms for Software in this Agreement apply to any Updates and Supplementary Software, unless <strong>AssistanZ</strong> provides different terms. <strong>AssistanZ</strong> may cease making available Supplementary Software and Internet-based services used with the Software at any time.</p>
 
<p><strong>2.3 Open Source Software.</strong> The Software may contain or be provided with components subject to the terms and conditions of "open source" software licenses (<strong>"Open Source Software"</strong>). To the extent required by the license that accompanies the Open Source Software, the terms of such license will apply in lieu of the terms of this Agreement with respect to such Open Source Software, including any provisions governing access to source code, modification or reverse engineering.</p>
 
<p><strong>2.4 Evaluation Software.</strong> This paragraph applies to any Software that <strong>AssistanZ</strong> makes available on an evaluation basis (<strong>"Evaluation Software"</strong>). End User may only use the Evaluation Software for internal evaluation purposes for the period specified by <strong>AssistanZ</strong> (or, if not specified, for 30 days), and may only permit a limited number of users (specified by <strong>AssistanZ</strong>) to access the Evaluation Software. After the evaluation period, End User must delete all copies of the Evaluation Software. End User acknowledges that Evaluation Software may not be fully functional. Not with standing anything else in this Agreement, <strong>AssistanZ</strong> does not offer any warranty, indemnity or support for any Evaluation Software.</p>
  
<p><strong>2.6 IP Protection.</strong> The Software has license protection mechanisms designed to manage and protect <strong>AssistanZ's</strong> intellectual property rights. Whether using Source Code or not, End User must not modify or alter these mechanisms or try to circumvent them or the usage rules they are designed to enforce.</p>

<h3>3. Important Customer Obligations</h3>
<p><strong>3.1 Accounts and Passwords.</strong> End User will provide accurate, current and complete information when registering with <strong>AssistanZ</strong> and ordering Products and agrees to update its information if it changes. This is important, because <strong>AssistanZ</strong> may send notices, statements and other information to End User by email. End User will keep all its Authorised Resources passwords and usernames confidential and will not share them with third parties. End User is responsible for all actions taken through its accounts.</p>
<p><strong>3.2 Conditions on Use of Products.</strong> End User will not, and will not allow any User or other third party to: (a) resell, assign, rent, give, transfer, pass title to, lease, copy, provide access to or sublicense (including without limitation on a timeshare, subscription service or outsourced basis) any Product to any third party (for use in its business operations including Customers) in accordance with this express terms of this Agreement, or permit anyone to use any data or information not owned by End User that is generated by the Products (and, in the event End User grants any security interest in any Products, the secured party has no right to use or transfer the Products); (b) use any Product to provide, or incorporate any Product into any product or service provided to, a third party, except as expressly permitted above for Customer Use; (c) reverse engineer, decompile, disassemble, decipher, decrypt, or otherwise seek to discover or obtain the source code or non-public APIs to Products (including any data structure or similar materials produced by the Products), except to the extent expressly permitted by applicable law despite this prohibition (and then only upon advance notice to <strong>AssistanZ</strong>); (d) modify, adapt or create derivative works of a Product (excluding End User Modifications and End User Plug-ins); (e) remove or obscure any proprietary or other notices of <strong>AssistanZ</strong> or any third party contained in any Product (including any information or data generated by the Products); (f) publicly disseminate information regarding the performance of Products; (g) use any Product for commercial solicitation purposes or spam; (h) use the <strong>AssistanZ</strong> name or any <strong>AssistanZ</strong> trademarks or logos except as permitted in Section 3.3 (Attribution); or (i) commit any act or omission that could result in damage to <strong>AssistanZ's</strong> or its supplier's or licensor's reputations. End User will not attempt to do any of the foregoing, encourage others to do so, or otherwise attempt to bypass or circumvent any usage restrictions in this Agreement.</p>
 
<p><strong>3.3 Attribution.</strong> In any use of the Software, End User must include the following attribution to <strong>AssistanZ</strong> on all user interfaces in the following format: "Powered by <strong>FogPanel</strong>", which must in every case include a hyperlink to  <a href="http://www.fogpanel.com" target="_blank">http://www.fogpanel.com</a>, and which must be in the same format as delivered in the Software.</p>
  
<p><strong>3.4 Indemnification.</strong> End User will indemnify, defend and hold harmless <strong>AssistanZ</strong> from and against any and all claims, costs, damages, losses, liabilities and expenses (including reasonable attorney's fees and costs) arising out of or in connection with any claim arising from or relating to (a) any breach by End User (including any Authorized Resources) of this Agreement, (b) any End User Data, (c) any End User Modifications, End User Plug-ins or other modifications of or combinations with a Product, or any service or product offered by End User in connection with or related to a Product, (d) any Uncontrolled Systems, or (e) any representations or warranties made by End User (including any Authorized User) regarding a Product to third parties. This indemnification obligation is subject to End User receiving (i) prompt written notice of such claim (but in any event notice in sufficient time for End User to respond without prejudice); (ii) the exclusive right to control and direct the investigation, defence, or settlement of such claim, provided that <strong>AssistanZ</strong> may participate in the claim at its own expense and End User may not settle any claim without <strong>AssistanZ's</strong> prior written consent; and (iii) all reasonable necessary cooperation of <strong>AssistanZ</strong> at End User's expense.</p>

<h3>4. Fees and Payment</h3>
<p><strong>4.1 General.</strong> End User must pay all fees by their due date specified at the time of order or otherwise within 30 days of <strong>AssistanZ's</strong> invoice or notice. Late payments are subject to interest charges of 1.0% per month on any outstanding balance, or the maximum permitted by law, whichever is less, plus all collection expenses. End User will continue to be charged during any period of suspension. In event of any termination, End User will pay the unpaid balance due calculated in accordance with this section and this Agreement. <strong>AssistanZ</strong> may charge such unpaid fees and charges to End User's credit card or otherwise bill End User for such unpaid fees and charges. End User acknowledges that it is not relying on the future availability of any Products in agreeing to or making its payments here under.</p>
<p><strong>4.2 Taxes.</strong> Payments made by End User under this Agreement exclude any taxes or duties payable in respect of the Products in the jurisdiction where the payment is either made or received. To the extent that any such taxes or duties are payable by <strong>AssistanZ</strong>, End User must pay to <strong>AssistanZ</strong> the amount of such taxes or duties in addition to any fees owed under this Agreement. Notwithstanding the foregoing, End User may have obtained an exemption from relevant taxes or duties as of the time such taxes or duties are levied or assessed. In that case, End User will have the right to provide to <strong>AssistanZ</strong> with any such exemption information and <strong>AssistanZ</strong> will use reasonable efforts to provide such invoicing documents as may enable End User to obtain a refund or credit for the amount so paid from any relevant revenue authority if such a refund or credit is available.</p>

<h3>5. License Certifications and Audits</h3>
<p>Upon <strong>AssistanZ's</strong> written request, End User will provide <strong>AssistanZ</strong> with a signed certification certifying that all Products are being used pursuant to the terms of this Agreement, including any access and user limitations. With prior reasonable notice of at least ten (10) days, <strong>AssistanZ</strong> (or its authorized agent) may audit the use of the Products by End Users, provided such audit is during regular business hours. End User will provide reasonable assistance and access to information in the course of any audit. End User is responsible for such audit costs only in the event the audit reveals that End User's use of the Products is not in accordance with the permitted scope of use. In the event that any certification or audit reveals that End User has exceeded its permitted number of Authorised Resources, <strong>AssistanZ</strong> may invoice End User for any past or ongoing excessive use and End User will pay the invoice in accordance with Section 4 (Fees and Payment). This remedy is without prejudice to any other remedies available to <strong>AssistanZ</strong> at law or equity or under this Agreement.</p>

<h3>6.AssistanZ’s Ownership Rights; Feedback</h3>
<p><strong>AssistanZ</strong> reserves all rights not expressly granted to End User in this Agreement. The Products (including any content or information contained therein) and all copies there of are protected by copyright and other intellectual property laws and treaties. <strong>AssistanZ</strong> <em>owns the title, copyright, and other intellectual property rights in the Products and</em> all copies, modifications and derivative works of the Products and underlying software (<strong>"AssistanZ Networks"</strong>), and End User does not acquire any ownership rights in <strong>AssistanZ Networks</strong>. All Products are licensed, not sold.</p>

<h3>7. Confidentiality </h3>
<p>Except as otherwise set forth in Section 6 (<strong>AssistanZ's</strong> Ownership Rights; Feedback) above, each party agrees that all code, inventions, know-how, business, technical and financial information it obtains (<strong>"Receiving Party"</strong>) from the disclosing party (<strong>"Disclosing Party"</strong>) constitute the confidential property of the Disclosing Party (<strong>"Confidential Information"</strong>), provided that it is identified as confidential at the time of disclosure or should be reasonably known by the Receiving Party to be Confidential Information due to the nature of the information disclosed and the circumstances surrounding the disclosure. Any <strong>AssistanZ</strong> technology, performance information relating to the Products, and the terms and conditions of this Agreement shall be deemed Confidential Information of <strong>AssistanZ</strong> without any marking or further designation. Except as expressly authorized herein, the Receiving Party will hold in confidence and not use or disclose any Confidential Information. The Receiving Party's nondisclosure obligation shall not apply to information which the Receiving Party can document: (i) was rightfully in its possession or known to it prior to receipt of the Confidential Information; (ii) is or has become public knowledge through no fault of the Receiving Party; (iii) is rightfully obtained by the Receiving Party from a third party without breach of any confidentiality obligation; (iv) is independently developed by employees of the Receiving Party who had no access to such information; or (v) is required to be disclosed pursuant to a regulation, law or court order (but only to the minimum extent required to comply with such regulation or order and with advance notice to the Disclosing Party). The Receiving Party acknowledges that disclosure of Confidential Information would cause substantial harm for which damages alone would not be a sufficient remedy, and therefore that upon any such disclosure by the Receiving Party the Disclosing Party shall be entitled to appropriate equitable relief in addition to whatever other remedies it might have at law.</p>

<h3>8. Termination</h3>
<p>This Agreement will continue so long as End User has a license to the Software unless earlier terminated. <strong>AssistanZ</strong> may suspend or terminate this Agreement and End User's account if End User fails to comply with the terms and conditions of this Agreement, including any failure to pay fees when due. <strong>AssistanZ</strong> may terminate any free account or evaluation usage at any time in its sole discretion.</p>
<p>End User may terminate this Agreement at any time with notice to <strong>AssistanZ</strong>.</p>
<p>Immediately upon termination of any license or subscription right granted under this Agreement, End User's license to the Software and will cease, and End User must at its own cost: (a) cease using (and require all Authorized Users, and anyone else to cease using) all the terminated Products; (b) remove all copies of Software from its computer systems and any Uncontrolled Systems; and (c) return to <strong>AssistanZ</strong> all Software or provide <strong>AssistanZ</strong> with written certification that it has destroyed all copies of the Software and other <strong>AssistanZ</strong> Confidential Information in its possession, custody or control. Upon termination of this Agreement for whatever reason, End User will not be entitled to credits or refunds for any unused portion of this Agreement, including but not limited to unused maintenance and support.</p>
<p>All payment and other obligations accrued as of the date of any expiration or termination of this Agreement, and Sections 3.2 (Conditions on Use of Products), 3.4 (Indemnification), 4. (Fees and Payment), 5. (License Certifications and Audit), 6. (<strong>AssistanZ's</strong> Ownership Rights; Feedback); 7. (Confidentiality), 8. (Termination), 10. (Warranties; Disclaimer of Warranties), 11. (Limitation of Liability), 12. (Publicity Rights) 13. (Assignment), 14. (Governing Law and Jursidiction), 15. (Copyright Infringement Notices), and 16. (General) will survive expiration or termination.</p>

<h3>9. <strong>AssistanZ</strong> Infringement Indemnification</h3>
<p>Subject to the remainder of this Section 9, <strong>AssistanZ</strong> will indemnify, defend and hold End User harmless against a claim to the extent based on an allegation that End User's use of a Product (in the form provided by <strong>AssistanZ</strong>) in compliance with this <u>Agreement infringes a United States or European Union patent or registered copyright ("Claim"), and will pay those damages and costs finally awarded against End User by a court of competent jurisdiction, or agreed to in writing by <strong>AssistanZ</strong> as settlement</u>, as a result of such Claim, provided that <strong>AssistanZ</strong> is (i) promptly notified and furnished a copy of such Claim, (ii) given all relevant evidence in End User's possession, custody or control, and (iii) given reasonable assistance in and sole control of the defence there of and all negotiations for its settlement. <strong>AssistanZ</strong> will have no obligation to defend and no liability for any damages or costs to the extent that a Claim is based upon: (i) use of a Product in combination with any non-<strong>AssistanZ</strong> product, software or equipment; (ii) use of a Product in a manner or for an application other than for which it was designed or intended to be used, regardless of whether AssistanZ was aware of or had been advised of such use; (iii) modifications to a Product by any person or entity other than AssistanZ (including any End User Modifications); or (iv) other circumstances or occurrences that are covered in End User's indemnification obligations in Section 3.4.</p>
<p>If a Product becomes, or in the opinion of <strong>AssistanZ</strong> may become, the subject of a Claim, AssistanZ may, at its option and in its discretion: (i) procure for End User the right to use the Product free of any liability; (ii) replace or modify the Product to make it non-infringing; or (iii) terminate End User's right to continue using such Product and refund, in the case of Software, any license fees related to this Software paid by End User (depreciated on a three-year straight line basis).</p>
<p>This Section 9 states the sole liability of <strong>AssistanZ</strong> and the exclusive remedy of End User for any infringement of intellectual property rights in connection with any Product or other items provided by <strong>AssistanZ</strong> under this Agreement.</p>

<h3>10. Warranties; Disclaimers of Warranties</h3>
<p><strong>10.1 General.</strong> Each party represents and warrants that it has the legal power and authority to enter into this Agreement, and that, if End User is an entity, this Agreement and each order is entered into by an employee or agent of such party with all necessary authority to bind such party to the terms and conditions of this Agreement.</p>
<p><strong>10.2 DISCLAIMER OF WARRANTIES.</strong> TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, AND EXCEPT AS EXPRESSLY SET FORTH HEREIN, ASSISTANZ PROVIDES THE PRODUCTS (INCLUDING THE SOFTWARE AND ANY MAINTENANCE) AS IS AND WITH ALL FAULTS, AND HEREBY DISCLAIM ALL OTHER REPRESENTATIONS, WARRANTIES AND GUARANTEES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR ANY PURPOSE. WITHOUT LIMITING THE FOREGOING, ASSISTANZ MAKES NO REPRESENTATION, WARRANTY OR GUARANTY (1) AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, TRUTH, AVAILABILITY, ACCURACY OR COMPLETENESS OF ANY PRODUCTS OR ANY CONTENT THEREIN OR GENERATED THEREWITH, (2) THAT (A) THE USE OF ANY PRODUCTS WILL BE SECURE, TIMELY, UNINTERRUPTED OR ERROR-FREE OR OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM OR DATA, (B) THE PRODUCTS WILL MEET END USER'S REQUIREMENTS OR EXPECTATIONS, (C) ANY STORED DATA WILL BE ACCURATE OR RELIABLE OR THAT ANY STORED DATA WILL NOT BE LOST OR CORRUPTED, (D) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY END USER THROUGH THE PRODUCTS WILL MEET END USER'S REQUIREMENTS OR EXPECTATIONS, (E) ERRORS OR DEFECTS WILL BE CORRECTED, OR (F) THE PRODUCTS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WITHOUT LIMITING THE FOREGIONG, TO THE MAXIMUM EXTENT PERMITTED BY APPLICBLE LAW, <strong>ASSISTANZ</strong> MAKE NO REPRESENTATIONS OR WARRANTIES WHATSOEVER WITH RESPECT TO, AND ASSUME NO LIABILITY FOR, ANY PRODUCTS PROVIDED ON AN EVALUATION BASIS. IN ADDITION, ASSISTANZ SHALL NOT BE LIABLE FOR DELAYS, INTERRUPTIONS, SERVICE FAILURES AND OTHER PROBLEMS INHERENT IN USE OF THE INTERNET AND ELECTRONIC COMMUNICATIONS OR OTHER SYSTEMS OUTSIDE THE REASONABLE CONTROL OF ASSISTANZ.</p>
<p>END USER MAY HAVE OTHER STATUTORY RIGHTS. HOWEVER, TO THE FULL EXTENT PERMITTED BY LAW, THE DURATION OF STATUTORILY REQUIRED WARRANTIES, IF ANY, SHALL BE LIMITED TO THE LIMITED WARRANTY PERIOD.</p>

<h3>11. Limitation of Liability</h3>
<p><strong>11.1 MAXIMUM LIABILITY.</strong> EXCEPT WITH RESPECT TO AMOUNTS PAYABLE TO THIRD PARTIES PURSUANT TO THE PARTIES INDEMNIFICATION OBLIGATIONS IN SECTION 3.4 AND 10 OR END USER'S BREACH OF ANY LICENSE OR USE RESTRICTIONS RELATING TO THE PRODUCTS, NOTWITHSTANDING ANY DAMAGES EITHER PARTY MIGHT INCUR FOR ANY REASON WHATSOEVER, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE ENTIRE LIABILITY OF EITHER PARTY TO THIS AGREEMENT UNDER ANY PROVISION OF THIS AGREEMENT AND THE OTHER PARTY'S EXCLUSIVE REMEDY HEREUNDER SHALL BE LIMITED TO THE ACTUAL DAMAGES SUCH PARTY INCURS, UP TO THE AMOUNT ACTUALLY PAID BY END USER FOR (A) SUCH SOFTWARE, DEPRECIATED ON A THREE-YEAR STRAIGHT LINE BASIS. TO THE MAXIMUM EXTENT PERMITTED BY LAW, EMBEDDED SOFTWARE LICENSOR'S WILL NOT BE LIABLE TO END USER FOR ANY DAMAGES WHATSOEVER, INCLUDING DIRECT DAMAGES OR THE TYPES OF DAMAGES DISCLAIMED IN SECTION 11.2 BELOW.</p>
<p><strong>11.2 OTHER DISCLAIMERS.</strong> NOTWITHSTANDING ANYTHING ELSE IN THIS AGREEMENT, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, AND EXCEPT FOR END USER'S BREACH OF ANY LICENSE OR USE RESTRICTIONS RELATING TO PRODUCTS, IN NO EVENT SHALL EITHER PARTY (OR THEIR RESPECTIVE THIRD PARTY SUPPLIERS/LICENSORS) BE LIABLE FOR ANY SPECIAL, INCIDENTAL, PUNITIVE, INDIRECT, OR CONSEQUENTIAL DAMAGES (INCLUDING LOST PROFITS OR REVENUE) WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATED TO THIS AGREEMENT. END USER SPECIFICALLY UNDERSTANDS AND AGREES THAT ASSISTANZ(ON BEHALF OF ITSELF AND ITS THIRD PARTY SUPPLIERS/LICENSORS) DISCLAIMS ALL WARRANTIES AND LIABILITY WITH RESPECT TO LOSS, LOSS OF USE OR CORRUPTION OF ANY END USER DATA (OR OTHER DATA END USER MAY PROVIDE) AND THE COSTS OF PROCUREMENT OF ANY SUBSTITUTE GOODS.</p>
<p><strong>11.3 Failure of Essential Purpose.</strong> The parties agree that the limitations specified in this Section 11 will survive and apply even if any limited remedy specified in this Agreement is found to have failed of its essential purpose.</p>
<p><strong>11.4 Force Majeure.</strong> Neither party shall be liable hereunder by reason of failure or delay in the performance of its obligations hereunder (except for the non-payment of money) on account of strikes, shortages, riots, insurrection, war, acts of terrorism, fires, flood, storm, explosions, earthquakes, acts of God, governmental action, labor conditions, or any other cause which is beyond the reasonable control of the party.</p>

<h3>12. Publicity Rights</h3>
<p><strong>AssistanZ</strong> may identify End User as a customer in Product promotional material. End User may request that <strong>AssistanZ</strong> cease identifying End User at any time by submitting an email to <a href="mailto:sales@assistanz.com">sales@assistanz.com</a>. Requests may take 30 days to process.</p>

<h3>13. Assignment</h3>
<p>End User may not assign this Agreement without the prior written consent of <strong>AssistanZ</strong> (which consent will not be unreasonably withheld), provided that the assignee agrees to be bound by the terms and conditions contained in this Agreement. <strong>AssistanZ</strong> may assign its rights and obligations under this Agreement in whole or in part without consent of End User. Any permitted assignee shall be bound by the terms and conditions of this Agreement.</p>

<h3>14. Governing Law and Jurisdiction</h3>
<p>This Agreement is governed by the laws of India under Coimbatore jurisdiction, Tamil Nadu.</p>

<h3>15. Copyright Infringement Notices</h3>
<p><strong>If End User believes that any content on AssistanZ site or FogPanel site violates its copyright, it should notify AssistanZ's copyright agent in writing. The contact information for AssistanZ's copyright agent is at the bottom of this section. AssistanZ cannot take action unless End User gives us all the required information.</strong></p>
<p>In order for AssistanZ to take action, End User must do the following in its notice:</p>
<p>(i) Provide End User's physical or electronic signature; </p>
<p>(ii) Identify the copyrighted work that End User believe is being infringed;  </p>
<p>(iii) Identify the item that End User thinks is infringing and include sufficient information about where the material is located (including which website) so that AssistanZ can find it; </p>
<p> (iv) Provide AssistanZ with a way to contact End User (such as address, telephone number, or email); </p>
<p>(v) Provide a statement that End User believes in good faith that the item identified as infringing is not authorized by the copyright owner, its agent, or the law to be used by AssistanZ and </p>
<p> (vi) Provide a statement that the information End User provides in its notice is accurate, and that (under penalty of perjury), End User is authorized to act on behalf of the copyright owner whose work is being infringed. </p>

<p><u>Contact information for AssistanZ's copyright agent:</u><br>
<strong>CopyrightEnforcement</strong><br>
AssistanZ Networks Pvt. Ltd.<br>
1136 Jayyseeli Plazaa, Dr.Radhakrishnan road, Gandhipuram,<br>
Coimbatore, Tamil Nadu, India - 641012.<br>
E-Mail: <a href="mailto:copyright@assistanz.com">copyright@assistanz.com</a></p>
 
<h3>16. General</h3>
<p>This Agreement is the entire agreement between End User and <strong>AssistanZ</strong> relating to the Products and supersedes all prior or contemporaneous oral or written communications, proposals and representations with respect to the Products or any other subject matter covered by this Agreement. If any provision of this Agreement is held to be void, invalid, unenforceable or illegal, the other provisions shall continue in full force and effect. This Agreement may not be modified or amended except as described on the first page of this Agreement or otherwise with the written agreement of <strong>AssistanZ</strong> (which may be withheld in its complete discretion without any requirement to provide reasons). As used herein, "including" (and its variants) means "including without limitation" (and its variants). If either party to this Agreement breaches any provision of this Agreement relating to Confidential Information or intellectual property rights, there may not be an adequate remedy available solely at law; therefore, an injunction, specific performance or other form of equitable relief or monetary damages or any combination thereof may be sought by the injured party to this Agreement. No failure or delay by the injured party to this Agreement in exercising any right, power or privilege hereunder shall operate as a waiver thereof, nor shall any single or partial exercise thereof preclude any other or further exercise thereof or the exercise of any right, power or privilege hereunder at law or equity. The parties are independent contractors. This Agreement shall not be construed as constituting either party as a partner of the other or to create any other form of legal association that would give on party the express or implied right, power or authority to create any duty or obligation of the other party.</p>
<p><strong>Should you have any questions concerning this Agreement, or if you desire to contact AssistanZ for any reason, please contact us at <a href="mailto:sales@assistanz.com">sales@assistanz.com</a>.</p>
<p>AssistanZ understands that Product usage may be flexible and that End Users may identify new proposed uses for the Products. If End User has questions about whether a proposed use complies with these rules, <strong>please contact AssistanZ at <a href="mailto:sales@assistanz.com">sales@assistanz.com</a>.</p>