modules = {
    application {
        resource url:'js/application.js'
    }                    
    login {
        resource url:'css/bootstrap/bootstrap.min.css'
        resource url:'css/theme/fog-classic/fog-classic.css'
        resource url:'css/compiled/signin.css'
        resource url:'css/layout.css'
        resource url:'css/elements.css'
        resource url:'css/bootstrap/dojo-detail-wrap.css'        
    }    
    home {     
        resource url:'css/theme/fog-classic/fog-classic.css' 
        resource url:'js/dojo-1.8/dojox/form/resources/CheckedMultiSelect.css' 
        resource url:'css/theme/fog-classic/EnhancedGrid.css'   
        resource url:'css/theme/fog-classic/Editor_rtl.css'  
        resource url:'js/dojo-1.8/dojo/resources/dojo.css'
        resource url:'js/dojo-1.8/dojox/widget/Toaster/Toaster.css'
        resource url:'css/theme/fog-classic/calendar/Calendar.css'        
        resource url:'css/bootstrap/bootstrap.css'      
        resource url:'css/bootstrap/bootstrap-responsive.css'
        resource url:'css/bootstrap/bootstrap-overrides.css'   
        resource url:'css/bootstrap/dojo-detail-wrap.css'  
        resource url:'css/lib/font-awesome.css'
        resource url:'css/layout.css'
        resource url:'css/icons.css'         
        resource url:'css/theme/fog-classic/calendar/MonthColumnView.css'
        resource url:'js/dojo-1.8/FogPanel/themes/Wizard/Wizard.css'
        resource url:'js/dojo-1.8/FogPanel/themes/VerticalMenuBar/VerticalMenuBar.css'
        resource url:'js/dojo-1.8/FogPanel/themes/LanguageSelector/LanguageSelector.css'    
        resource url:'js/dojo-1.8/FogPanel/themes/ZoneSelector/ZoneSelector.css'            
        resource url:'js/dojo-1.8/FogPanel/themes/Navigator/Navigator.css'
        resource url:'js/dojo-1.8/FogPanel/themes/InstanceStatus/InstanceStatus.css'
        resource url:'js/dojo-1.8/dojox/image/resources/Lightbox.css'
        resource url:'js/dojo-1.8/dojox/image/resources/SlideShow.css'
        resource url:'js/dojo-1.8/dojox/image/resources/ThumbnailPicker.css'
        resource url:'js/dojo-1.8/dojox/image/resources/Gallery.css'
        resource url:'js/dojo-1.8/dojox/image/resources/Badge.css'
        resource url:'js/dojo-1.8/dojox/image/resources/Magnifier.css'
        resource url:'js/dojo-1.8/FogPanel/themes/WizardListItem/WizardListItem.css'
        resource url:'js/dojo-1.8/FogPanel/themes/WizardZoneInfo/WizardZoneInfo.css'
        resource url:'js/dojo-1.8/FogPanel/themes/ZoneItem/ZoneItem.css'
        resource url:'js/dojo-1.8/Zone/themes/ZoneCost/ZoneCost.css'     
//        resource url:'js/dojo-1.8/dojox/form/resources/FileInput.css'     
        resource url:'css/elements.css'
        resource url:'css/compiled/index.css'
        resource url:'css/elements.css'                                        
        resource url:'css/config/config.css'
        resource url:'css/setup.css'                            
        resource url:'css/compiled/new-user.css'
        resource url:'css/tables.css'
        resource url:'css/compiled/index.css'
        resource url:'css/report.css'         
    }                 
    user_index {
        resource url:'js/dojo-1.8/FogPanel/themes/VolumeListItem/VolumeListItem.css'
        resource url:'js/dojo-1.8/dojox/grid/resources/claroGrid.css'
        resource url:'js/dojo-1.8/FogPanel/themes/TemplateInfo/TemplateInfo.css'
        resource url:'js/dojo-1.8/List/themes/ListItem/ListItem.css'
        resource url:'js/dojo-1.8/dojox/mobile/themes/android/android.css'
    }
    
    home_index {
        resource url:'css/elements.css'                                        
        resource url:'css/config/config.css'
        resource url:'css/setup.css'                            
        resource url:'css/compiled/new-user.css'
        resource url:'css/tables.css'
        resource url:'css/compiled/index.css'
        resource url:'css/report.css'         
    } 
    signup {        
        resource url:'css/style.css' 
        resource url:'js/dojo-1.8/dojox/widget/Wizard/Wizard.css'                                                                                       
        resource url:'js/dojo-1.8/FogPanel/themes/Wizard/Wizard.css'                                         
    }
    
    mobile_android {  
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/common.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/Heading.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/View.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/ToolBarButton.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/RoundRect.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/EdgeToEdgeCategory.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/RoundRectCategory.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/RoundRectList.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/ListItem.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/Switch.css"      
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/Button.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/Carousel.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/CheckBox.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/ComboBox.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/android/FixedSplitter.css" 
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonWhitePlus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonWhiteMinus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonWhiteUpArrow.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonWhiteDownArrow.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonWhiteSearch.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonColorButtons.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonCheckboxOn.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonCheckboxOff.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonBlueCircleMinus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonBlueCirclePlus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonBlueCircleArrow.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonRedCircleMinus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonRedCirclePlus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonRedCircleArrow.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGreenCircleMinus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGreenCirclePlus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGreenCircleArrow.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonBlackCircleCross.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/IconContainer_keyframes.css"
        
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGrayRoundRect.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonSilverCircleDownArrow.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonSilverCircleGreenButton.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonSilverCircleGrayButton.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonSilverCircleOrangeButton.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonSilverCircleGreenPlus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonSilverCircleRedCross.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonBlueBall.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGreenBall.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonOrangeBall.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonRedBall.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonTransparent19.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonTransparent29.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonTransparent30.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonYellowStar.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGrayStar.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGrayCross.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonRedCross.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonWhiteCross.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGrayKnob.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGrayPlus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/domButtons/DomButtonGrayMinus.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/dissolve.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/cover.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/cube.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/reveal.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/slidev.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/coverv.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/revealv.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/swirl.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/scaleOut.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/scaleIn.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/swap.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/zoomOut.css"
        resource url:"js/dojo-1.8/dojox/mobile/themes/common/transitions/zoomIn.css"                
    }     
}
