define({
    root: {        
        root : "root",
        greeting : "",
        admin : {
            name : "Admin",
            administrator : "Administrator",
            contactAdmin : "Error contact admin"
        },
        common: {  
            vCPUCore: "vCPU",
            memory: "Memory",
            editOfferTitle : "Edit Computing Offer",
            free: "Free",
            serviceName:"Service Name",
            itemName:"Item Name",
            changedBy:"Changed By",
            oldCost:"Old Cost",
            newCost:"New Cost",
            changedDate:"Changed Date",
            selectVM : "Select Instance",
            selectTier : "Select Tier",     
            noVPCMsg: "You don't have any vpc yet, create one.",            
            noTierMsg : "You don't have any tier for this VPC! ",
            noVPCandTierMsg : "There is no Tier, create one VPC then add Tier",              
            noVPCandLBMsg : "There is no public LB, create one VPC then add public LB",
            noLBMsgInfo : "You don't have any public LB!",            
            noVPCandInternalLBMsg : "There is no internal LB, create APP tier then add internal LB",
            noInternalLBMsgInfo : "You don't have any internal LB",            
            noVPCandPublicIPMsg : "",
            noVPCPublicIPMsgInfo : "You don't have any public IP! create VPC and acquire IP",            
            noVPCandVMMsg : "There is no instance, create tier then add instance",                 
            noVMListMsg : " You don't have any instance yet, create one.",
            noStaticMsg: "Please goto public ip menu, then select ip, and  enable staticnat", 
            nopfMessage : "Please goto public ip menu, then select ip, and  configure portforwarding",
            noAcl : "No ACL",
            noVPCAvalilableMsg: "VPC is not available for basic zone",             
            topology: "VPC Topology",
            noVPC : "No VPC",
            noZone :  "No Zone",
            staticNat:"Static Nat",
            publicLbIP:"Public LB IP",
            virtualMachine:"Virtual Machine",
            internalLb:"Internal LB",
            privateGateways:"Private Gateways",
            publicIP:"Public IP",
            s2sVpn:"Site-to-Site VPNs",
            portForwardingIP:"Port Forwarding IP",
            networkAcl:"Network ACL",
            changeAcl:"Change ACL",
            router:"Router",
            userLabel: "User",
            selectZone: "Select Zone",
            selectACL : "Select ACL",
            noTier : "No Tier",
            selectNetworkOffer : "Select Network Offer",
            vpnCustomerGateway : "VPN Customer Gateway",
            ipsecPresharedKey:"IPsec Preshared-Key",
            vpn: "VPN",
            details: "Details",
            algorithm: "Algorithm",
            actions : "Action",            
            sourcePort: "Source Port",
            instancePort: "Instance Port",
            ruleNo :"Rule.No",
            protocolType : "Protocol Type",
            selectVPC : "Select VPC",
            selectVPNCustomer : "Select VPN Customer Gateway",
            allVPC : "All VPC",
            vpcName : "VPC Name",
            aclName : "ACL-Name",
            editRule : "Edit Rule",
            deleteRule : "Delete Rule",
            tiers : "Tiers",
            tier: "Tier",
            security: "Security",
            networkACL : "Network ACL",
            backtoDashboard : "Back to Cloud Service",
            locked:"Locked",
            lockTime:"Lock Time",
            yes:"Yes",
            no:"No",  
            cidr : "CIDR",
            customerGW: "Customer GW",   
            vpnPrivateGW: "VPN Private GW",   
            vpnConnection: "VPN Connection",  
            gateway : "Gateway",
            intheData : "in the zone",
            publicNw : "Public Nw",
            publicGateway : "Public Gateway",
            vpnGateway : "VPN Gateway",
            privateGateway : "Private Gateway", 
            vpnEnabled : "VPN Enabled",
            ivitationMailSucess : "Mail sent successfully to the users",
            resendInvitationSucess: "Invitation sent successfully",                        
            vpnEnabledError : "Cannot enable VPN, please contact admin.",
            vpnDisable : "VPN Disabled",
            vpnDisableError : "Cannot disable VPN, please contact admin.", 
            vpnDisableTitle :"Disable VPN",
            vpnEnableTitle :"Enable VPN",
            error: "Error",
            invalidEmail:"Invalid email",
            emailExist:"Email already exist",
            duplicateEmail : "Duplicate email",            
            createdDate : "Created Date",
            resend:"Resend",
            loadBalancer: "LoadBalancer",
            addVM: "Add Instance",
            removeVM: "Remove Instance",
            CostPerPolicyPerMonth: "Cost/Policy/Month",
            CostPerRulePerMonth: "Cost/Rule/Month",                   
            CostPerConnectionPerMonth: "Cost/Connection/Month",            
            policy:" Policy",
            rules:" Rules",            
            portForward: "Port Forwarding",
            comingSoon : "Coming Soon",
            notAvailable : "Not Available",
            selectNetwotk:"Select Netwotk",
            bit32 : "32bit",
            average:"Average",
            excellent:"Excellent",
            good:"Good",
            select: "Select",
            duplacateEmailMsg: "Email must be unique",
            loadBalancing:"Load Balancing",
            portForwarding:"Port Forwarding",
            unit: "Unit",
            networkType: "Network Type",
            supportedService:"Supported Service",
            bit64 : "64bit",
            networkName:"Network Name",
            ipAddress :"IP Address",
            defaultVal: "Default",
            computingOffers : "Computing Offers",
            diskOffers : "Disk Offers",  
            templates: "Templates",
            bandwidthMiscInfo:"Bandwidth Mics Info",
            ipMiscInfo:"IP Mics Info",
            snapshotMiscInfo: "Snapshot Mics Info",
            vmSnapshotMiscInfo: "VM Snapshot Mics Info",   
            networkOffer: "Network Offer",            
            prepaidPaymentMessage:"Make payment to proceed further!",
            hypervisor:"Hypervisor",
            CostPerGBPerMonth : "Cost/GB/Month",
            zoneCostInvalidMsg : "Cannot Be Null",
            exceedBandwidthCost : "Excess Bandwidth Cost/GB/Month",
            vmRunningCostPerMonth : "Instance Running Cost/Month",
            vmStopageCostPerMonth : "Instance Stopage Cost/Month",            
            setupCost : "Setup Cost",            
            runningCostPerHr : "Instance Running Cost/HR",            
            stopageCostPerHr : "Instance Stopage Cost/HR",    
            perGBPerHr : "Per GB/Hour",
            oneTime: "Once",
            manual: "Manual",
            storageCostPerMonth : "Volume Cost/Month",      
            costPerGBMonth : "Cost/GB/Month",                  
            costFor : "Cost for",                  
            strong : "Strong",
            setasDefault: "Set as Default",
            allocated: "Allocated",
            selectNic:"Select Nic",
            falseData : "false",
            medium : "Medium", 
            custom : "Custom",
            disable : "Disable",
            inactive: "Inactive",
            enabled : "Enabled",
            disabled : "Disabled",            
            enable : "Enable",
            zone : "Zone",
            pod : "Pod",
            noNetworkOffer:"No Network Offering",
            noNetwork:"No Network",            
            selectOS : "Select OS",
            selectCategory : "Select Category",            
            cluster : "Cluster",            
            allZone : "All Zone",
            allPod : "All Pod",
            CostPerIPPerMonth : "Cost/IP/Month",
            CostPerMonth : "Cost/Month",
            allCluster : "All Cluster",            
            host : "Host",
            weak : "Weak",
            displayName : "Display Name",
            idCaps : "ID",
            email : "Email",
            gbPerMonth : "/GB/Month",
            countSummary : "Count Summary",
            gbPerHr : "/GB/Hr",
            amount : "Amount",
            type:"Type",            
            netmask:"Netmask",
            taxAmount : "Tax Amount",
            level : "Level",
            allPlan:"All Plan",
            allUser:"All User",
            state : "State",
            name: "Name",
            bottom : "Bottom",
            open: "Open",
            close : "Close",
            active:"ACTIVE",
            selectReply:"Selct Reply",
            inProgress:"In Progress",
            closed : "Closed",
            staff : "Staff",
            ips:"IPs",
            client : "Client",
            clients : "Clients",            
            onHold : "On Hold",
            description : "Description",
            baseOSName : "Base OS",
            operatinSystem : "Operating Stystem",
            gb: "GB",            
            privatePort :"Private Port",
            publicPort :"Public Port",
            vmList :"Instance List",
            vm:"Instance",
            enableStaticNat:"Enable Static NAT",
            disableStaticNat:"Disable Static NAT",
            core: "Core",            
            mb: "MB",
            MBs : "MB/s",
            month : "Month",  
            hour : "Hour",
            billingCostPeGBHR : "(Billing Cost)Per GB/per HR",
            cost : "Cost",
            unitCost : "unitCost",
            runningCost : "Running Cost",            
            cpu : "CPU", 
            vcpus: "VCPUs",
            speed : "Speed",
            mhz: "MHz",
            date : "Date",
            deleteData : "Delete",
            startDate:"Start Date",
            endDate:"End Date",
            maxUses:"Max Uses",
            promotionValue:"Promotion Value",
            value:"Value",
            uses:"Uses",
            promotionType:"Type",
            notes:"Notes",
            code:"Code",
            reset : "Reset",
            action : "Action",            
            all : "All",
            empty : "Empty",
            event : "Event",
            network:"Network",
            dd : "DD",
            mm : "MM",
            yyyy : "YYYY",     
            view : "View",
            viewed : "Viewed",
            trialLimit : "Trial Limit",
            mbOfMemory : "MB of memory",
            amountSummary : "Amount Summary",
            edit:"Edit",
            downloadPDF : "Download pdf",
            viewInvoice : "View Invoice",
            primaryStorage : "Primary Storage",
            resetPassword:"Reset Password",
            showApiKey:"Show API Keys",
            resetApiKey:"Reset API Keys",
            revokeApiKey:"Revoke API Access",
            grantApiKey:"Grant API Access",
            noDepartment:"No Department",
            gatewayName:"Gateway Name",
            gatewayType:"Gateway Type",
            gatewayEnableDisable:"Enable / Disable",
            gatewayIsDefault:"Is Default",
            gatewayIncludeExclude:"Include / Exclude",
            procFeePercent:"Processing Fee Percent",
            procFeeAmount:"Processing Fee Amount",
            vpc: {
                name: "VPC",
                yourVpc : "Your VPC",
                vpcs : "VPC's",
                tiers: "Tiers",
                instance: "Instance",
                publicLB : "Public LB",
                internalLB :"Internal LB",
                publicIPAdd : "Public IP Add",  
                publicIP : "Public IP",                  
                staticNat : "Static Nat"
            },
            menu : {
              home: "Home",
              cloud: "Cloud",
              instance: "Instances",
              storage: "Storages",
              snapShot: "Snapshots",
              firewall: "Firewalls",
              network: "Networks",
              health: "Health",
              services : "Services",
              sshKey : "SSH Keys",
              bandwidth : "Bandwidth",
              ipManager : "IP Manager",
              templates : "Templates",
              billing : "Billing",
              currentUsage : "Current Usage",
              invoice : "Invoice",
              payments : "Payments",
              recurringItems : "Recurring Items",
              support : "Support",
              Stats : "Stats",
              billableItem : "Billable Item",
              paymentReport : "Payment Report",
              activity : "Activity",
              events : "Events",
              alerts : "Alerts",
              notifications : "Notifications",
              limitSummary:"Resource Limit"
          },
            apiMessage :{
               resetKey:"Reset API Key Sucess!",
               revokeKey:"Revoke API Key Sucess!",
               grantKey:"Grant API Key Sucess!"
            },
            exceptionMsg : {
                validationException : "ValidationException",
                cardVerificationFailed : "Card verification failed",
                unabletoVerifyCard : "Unable to verify card,  please try again",
                unabletoCreateAccount : "Unable to create account, please try again or contact your admin"
            },
            cloudStack : {
                errorMessage : "Unable to process your request please contact admin"
            },
            password:{
                notMatch : "Password Donot Match",
                lengthConstrain : "Password length must be min 8 and max 15 characters",
                tooShort:"Too short",
                strong:"Strong",
                medium:"Medium",
                weak:"Weak",
                resetVMPassword : "Reset Instance Password"
            },
            username:{
                valid:"Username already exist",
                exists:"Username already exist",
                inValid:"Invalid username or user name length is Invalid"
            },
            account : {                
                name : "Account",
                accountType : "Account Type",
                exceededBy : "Exceeded by",
                selectCountry :"Select Country",
                selectState : "Select State",
                passworResetSuccess : "Successfully reset password",
                oldPasswordNotMatch : "Old Password Donot Match",
                passwordNotMatch : "Password Donot Match",
                passwordShouldEmpty : "Password should not be empty",
                passwordLengthConstrain : "Password length must be min 8 and max 15 characters",
                mailSentSucessMessage : "Mail sent successfully , please login your mail to reset password",
                mailSentSucessActivationMessage : "Mail sent successfully , please login your mail to activate your account",
                accountCancelled : "Account cancelled!",
                accountCancelError : "Cannot cancel account!",    
                accountEnabled : "Account enabled!",
                accountEnabledError : "Cannot enable account!",
                accountDisabled : "Account disabled!",
                accountDisabledError : "Cannot disable account!",
                accountSuspended: "Account suspended!",
                accountSuspendError: "Cannot suspend account!",     
                amountRefunded:"Amount Refunded!",
                amountRefundError:"Cannot refund amount!",
                accountLocked : "Account locked!",
                accountLockError : "Cannot lock account!",         
                accountUnlocked : "Account Unlocked!",         
                accountUnlockedError : "Cannot unlock account!",         
                resetPasswordSucess : "Reset password success!",
                resetPasswordError : "Cannot reset password!",   
                type : {
                    RETAIL : "RETAIL",
                    TRIAL : "TRIAL"                    
                },
                status : {             
                    ACTIVE : "ACTIVE",
                    BLOCKED : "BLOCKED",
                    LOCKED : "LOCKED",
                    DISABLED : "DISABLED",
                    NOT_VERIFIED : "NOT_VERIFIED",
                    SUSPENDED : "SUSPENDED",
                    CANCELED:"CANCELED",
                    CLOSED : "CLOSED",                    
                    active : "Active",
                    blocked : "Blocked",
                    locked : "Locked",
                    Disabled : "Disabled",
                    NotVerified : "NotVerified",
                    suspended : "Suspended",
                    canceled : "Canceled",
                    closed : "Closed",
                    verified : "Verified",
                    notVerified : "Not Verified"
                }
            },
            baseOS : {
                linux : "Linux",
                windows : "Windows"
            },
            size : {
                sizeName : "Size",
                minSize : "Min Size",
                maxSize : "Max Size"
            },
            status : {
                ready : "Ready",
                name:"Status"
            },
            ip : {
                name : "IP",
                invalidAcquireIpMessage : "Cannot Acquire IP! Contact Admin",
                acquireIp : "IP acquired successfully",
                acquire : "Acquire",                
                revoke: "Revoke",
                releaseIP : "Release IP",
                ipReleased : "IP released successfully",                
                cannotReleaseIP : "Cannot Release IP! Contact Admin",
                noSecondaryIP : "No Secondary IP available! ",
                userDidntAquireIP : "User did not acquired any IP's yet"
            },
            message: {
                createStaticRoute:"Added static route successfully",
                privateGatewayDelete:"Deleted private gateway successfully",
                deleteStaticRoute:"Deleted static route successfully",
                createS2SCustomerGateway:"Added VPN customer gateway successfully",
                createVPCGateway:"Added VPC Private gateway successfully",
                deleteS2SCustomerGateway:"Deleted VPN customer gateway successfully",
                updateS2SCustomerGateway:"Updated VPN customer gateway successfully",
                createVPNConnection:"Added VPN connection successfully",
                deleteVPNConnection:"Deleted VPN connection successfully",
                restartVPNConnection:"Restarted VPN connection successfully",
                addS2SvpnSuccess:"Created site to site VPN successfully",
                deleteS2SvpnSuccess:"Deleted site to site VPN successfully",
                networkAclRuleDeleted : "Rule deleted successfully",
                aclChanged:"ACL Updated successfully",
                aclRuleUpdatedSuccess : "Rule updated successfully",
                tierEdidtedSuccess:"VPC tier updated successfully",
                selectTier:"Select Tier",
                releaseVpcIPSuccess : "IP address removed from this VPC successfully",
                addIpToVpcSuccess : "IP address added to this VPC successfully",
                invitationSuccess:"Invitation mail sent successfully",
                vpcCreated:"VPC created successfully",
                tierCreate:"VPC tier created successfully",
                internalLBCreate:"InternalLB created successfully",
                internalLBDeleted:"InternalLB deleted successfully",
                tierDeleted:"VPC tier deleted successfully",
                tierRestartSuccess:"VPC tier restarted successfully",
                vpcDeleted:"VPC deleted successfully",
                vpcUpdateSuccess:"VPC updated successfully",
                aclRuleCreated:"ACL rule created successfully",
                vpcRestartSuccess:"VPC restarted successfully",
                networkAclCreated:"Network ACL created successfully",
                networkAclDeleted:"Network ACL deleted successfully",
                vpnUserSucess : "New user created for this VPN",
                allVMAddedToLB : "All available Instance are added to this LoadBalancer",
                noVMAddedToLB : "No Instance available for this LoadBalancer to remove",
                vpnUserFailed : "Cannot create user for this account, please contact admin.",
                vpndeleteUserSuccess : "VPN user deleted successfully",
                vpndeleteUserError : "Cannot delete this VPN user, please contact admin",           
                vpnEnalbed : "VPN Enabled for this IP",
                vpnEnalbedError : "Cannot enabled VPN for this IP",
                vpnDisabled : "VPN disabled for this IP",
                vpnDisabledError : "Cannot disabled VPN for this IP",                
                networkCreate: "Network created successfully",
                nicCreated:"NIC create successfully",
                nicDeleted:"NIC deleted successfully",
                pullPlanSuccess:"All plans are pulled from CloudStack",
                pullTemplateSuccess:"All templates are pulled from CloudStack",
                setDefaultNicsuccess:"Set default NIC success for this Instance",
                nicfailed : "Cannot create NIC please contact admin",                
                networkUpdated: "Network updated successfully",
                networkDelete:"Network deleted successfully",
                selectIp:"select IP",
                enableStaticNatSuccess:"Static NAT enabled successfully",
                disableStaticNatSuccess:"Static NAT disabled successfully",
                addPortForwardingRuleSuccess:"Port forwarding rule added successfully",
                selectVM:"Please select an Instance",
                ruleUpdateSuccess:"Rule updated successfully",
                addLoadBalancerRuleSuccess:"Added load balancer successfully",
                addAdditionalVMToLoadBalancerRuleSuccess:"Instance added to this policy successfully",
                removeVMFromLoadBalancerRuleSuccess:"Instance removed from this policy successfully",
                addFirewallRuleSuccess:"Firewall added successfully for this IP Address",
                addIpToNetworkSuccess:"IP acquired for this network successfully",
                networkHasFirstIPMessage:"You already acquired a free IP, Create instance to acquire a new IP",
                releaseIPSuccess:"IP is Released for this network successfully",
                selectHypervisor:"Select Hypervisor",
                selectFormat:"Select Format",                
                noHypervisor:"No Hypervisor",
                noCode : "No code",
                added : "Added",
                created : "Created !",
                createdError : "Created Template Failed!",                
                noTag : "No Tag",
                connecting : "Connecting...",
                excesBandwidthCostMsg : "Excess Bandwidth Cost/GB/Month",
                oneTimeChargeTemp : "one time charge template must have a cost!",
                oneTimeChargeTemplate : "one time charge template!",    
                vmExistMsg : "Instances are available with this computing offer.",
                volumeExist : "volumes are available with this disk Offer.",
                successfully : "successfully",
                addedSuccess : "Added successfully!",
                updatedSuccess : "Updated successfully!",    
                templUpdated : "Template updated!",
                updatedError : "Cannot be updated !",                   
                departmentAdded:"Department added!",
                noPreDefinetReply:"No pre definedReply",
                addEgressRuleSuccess:"Egress rule added successfully",
                cloudStackError:"Error",
                itemAdded : "Item added",
                ItemDeleted : "Item deleted",  
                ItemUpdated : "Item updated",                 
                ItemUpdateError : "Cannot update this item",                     
                cannotDelete : "Cannot be deleted!",
                enterContent : "Please enter content!",
                cannotBeAdded : "Cannot be added!",
                configMissing : "Config missing!",  
                deletedSuccess : "Deleted successfully",
                trialAccountResource : "Trial account resource limit reached!",
                updateSuccess: "successfully updated",
                deletedJobSuccess : "Deleted job successfully",
                failed: "Failed",
                inProgress : "In Progress",  
                success: "Success!",
                refreshPage : "Please refresh page",
                noDisk:"No Disk",
                selectPlan : "Select Plan",  
                noPlan: "No Plan",
                failedContactAdmin : "Failed! please contact admin",
                contactAdmin : "Please contact admin.",
                resetPassworSuccess : "Reset password success",
                selectOffer : "Select Offer",
                selectComputingOffer : "Select Computing Offer",
                selectTemplate : "Select Template",
                selectFirewall : "Select Firewall",
                selectNetwork: "Select Network",
                selectZone : "Select Zone",
                selectPode : "Select Pod",
                selectCluster : "Select Cluster",  
                selectTag : "Select Tag", 
                hostTag : "Host Tag",                 
                selectDiskOffer : "Select Disk Offer",
                selectDisk : "Select Disk",          
                selectInstance : "Select Instance",                          
                noThanks : "No Thanks",
                noTemplate : "No Template",
                noFirewall: "No Firewall",
                addTemplateError : "Cannot add template",
                addTemplateSuccess : "Template created",
                usedBandwidth : "Used  Bandwidth(GB)",
                excedded : "Exceeded (GB)",
                totalBandwidth : "Total  Bandwidth",
                addInvoiceItem:"Cannot add item! No draft invoice",
                itemDeleted:"Item deleted",                
                noHostAvailable : "No hosts are avaialble for migration",
                confirmMigratVM : "Please confirm that you want to migrate instance to another Host",
                confirmAnotherMigratVM : "Please confirm that you want to migrate instance to another Primary Storage",
                cannotMigrateInstance : "Cannot migrate instance !",
                vmMigratSucess : "Instance migrated successfully",                
                discountDisableInfo:"Discount is disabled for monthly instance",
                discountDisableVMInfo:"Discount is disabled for compute offer",
                discountErrorInfo:"all account are added in this start and end date",
                cloudStackConfigMissing:"Config missing!",
                noVMSnapforTrial:"This option is not available for trial account",
                gatewayAdded:"Gateway details updated",
                gwADVDuplicate:"More than one advanced gateway cannot be added",
                missingDefaultGW:"Kindly select a default gateway",
                correctGateway:"Select only enabled gateway as a default one"
            },
            instance : {
                vmStartedSuccessMessage: "Instance started successfully",
                vmStoppedSuccessMessage : "Instance stopped successfully",
                vmRestartSuccessMessage : "Instance restarted successfully",                
                createVM : "Create Instance",
                instanceIP : "Instance IP",
                name : "Instance",
                vmName : "Instance Name",
                selectInstance : "Please select a instance",
                creatingInstance : "Creating Instance Please wait",
                vmError : "Cannot create instance please contact admin",
                created : "Instance Created",
                startVMError : "Cannot Start Instance !",
                vmStarted : "Instance Started",
                vmStopped : "Instance Stopped",                
                stopVMError : "Cannot Stopped Instance !",
                deleteVMError : "Cannot Delete Instance!",
                vmDeleted : "Instance Deleted",
                rebootVMError : "Cannot Reboot Instance !",
                vmRebooted : "Instance Restart Success",
                restoreVMSucess : "Restores Instance successfully!",
                restoreVMError : "Cannot Restore Instance !",
                resetVMError : "Cannot Reset Instance!",     
                resetVMSucess : "has been reset",                     
                selectDVDDrive : "Select DVD Drive",
                connotAttachIso : "Cannot Attach ISO",
                volumeCountReachedTrial: "Volume Count reached for Trial Account!",
                volumeCountReachedVm: "Volume Count reached for this instance",
                isoAttached : "ISO Attached",
                isoAttachedError : "Cannot Attach ISO",
                isoDettachedError : "Cannot Dettach ISO",
                isoDettached : "ISO Detached",     
                cannotAddVolume : "Cannot add Volume",
                vmNameChanged : "Display name has been changed",
                mbOfMemory : "MB of memory",
                planChanged : "Plan changed",
                planChangedError : "Change plan failed! please contact admin",     
                noSSHKey : "No SSh Key! Create Key to change from default key ",
                sshKeyChanged : "SSH Key Changed",
                startConsole : "Start Console",
                status : {
                    running : "Running",
                    stopped : "Stopped",
                    destroyed : "Destroyed",
                    starting : "Starting",
                    stopping : "Stopping",
                    exbunging : "Expunging"                    
                }
            },
            template : {
                centOS : "CentOS",
                debian : "Debian",
                oracle : "Oracle",
                redHat : "RedHat",
                SUSE   : "SUSE",
                windows: "Windows",
                novel  : "Novel",
                unix   : "Unix",
                ubuntu : "Ubuntu",
                name: "Template",
                noTemplate : "No Templates",
                noLinuxTemplate : "No Linux templates found.",
                noWindowsTemplate : "No Windows templates found",    
                deleteTemplateError : "Cannot Delete template !",
                deleteTemplateSuccess : "template Deleted",
                copyTemplate : "Copy Template",
                noAppTemplateFound : "",
                deleteTempFailed : "Failed to delete this template",
                deleteTempSuccess : "Template deleted successfully",                
                grid : {
                    templateName : "Template Name",
                    operationSystem : "Operating System",
                    osType : "OS Type",
                    zone : "Zone",
                    cost : "Cost"      
                }   
            },
            firewall : {
                name : "Firewall",
                noOutboudData : "There is no outbound data",
                firewallSuccess : "Firewall Added successfully!",
                firewallError : "Cannot Add Firewall!",
                DeletedSuccess : "Deleted successfully",                
                firewallLoading : "Loading Firewall, Please wait...",
                noInboundRule : "You don't have inbound rule yet, create one",
                noOutboundRule : "You don't have outbound rule yet, create one",                
                inboundLoading : "Inbound Loading, Please wait...",
                outboundLoading : "Outbound Loading, Please wait...",                
                managePort : "Manage Ports",
                invalidCIDR : "Invalid CIDR",
                addEgressError : "Cannot Add Ingress!",
                protocol : "Protocol",
                startPort : "Start Port",
                startPortOrICMPType : "Start Port/Icmp Type",
                endPortOrICMPCode : "Start Port/Icmp Code",                
                endPort : "End Port",
                cidr : "CIDR",
                ruleDeleteSuccess : "Rule Deleted successfully",
                ruleDeleteError : "Cannot Delete this rule!",
                outboundAddError : "Cannot Add Outbound!",
                outboundAddSuccess : "Outbound Rule Added successfully!",                
                inboundAddError : "Cannot Add Inbound!",
                inboundAddSuccess : "Inbound Rule Added successfully!",                
                noInbound : "There is no inbound data",                
                networkUnreachable : "Network unreachable",
                hostUnreachable : "Host unreachable",
                protocolUnreachable : "Protocol unreachable",
                portUnreachable : "Port unreachable",
                fragmentationNeeded : "Fragmentation needed and don't fragment was set",
                sourceRouteFailed : "Source route failed",
                designationNetworkUnknown : "Designation network unknown",
                designationHostUnknown : "Designation host on known",
                sourceHostIsolated : "Source host isolated",
                networkAdministrativelyProhibited : "Network administratively prohibited",
                hostAdministrativelyProhibited : "Host administratively prohibited",
                networkUnreachableForTos : "Network unreachable for Tos",
                hostUnreachableForTos : "Host unreachable for Tos",                   
                datagramForNetwork : "Datagram for the network",    
                datagramForHost : "Datagram for the host",    
                datagramForTosAndNetwork : "Datagram for tos & network",    
                datagramForTosAndHost : "Datagram for tos & Host",                
                ttlExpiredTransit : "TTL expired transit",
                fragmentationReassenblyExceeded : "Fragmentation reassenbly exceed",                
                pointerIndicatesError : "Pointer indicates the error",
                missingRequiredOption : "missing a required option",
                badLength : "Bad length",
                icmpType : "ICMP Type",
                icmpCode : "ICMP Code",
                trafficType: "Traffic Type"
            },
            ticket : {
                ticketId : "Ticket ID",
                tockenNo : "Token.No",
                subject : "Subject",
                department : "Department",
                priority : "Priority",
                low: "Low",
                high : "High",
                normal : "Normal",
                postedDate: "Posted Date",
                ticketClosed : "Ticket Closed!",
                ticketAdded : "Ticket Added!",
                addTicketError : "Cannot Add Ticket!"
            },
            report : {   
                toDate: "toDate",
                fromDate : "fromDate",
                forDateRange : "forDateRange",           
                forAccount : "forAccount",
                forZone : "forZone",
                billableItemList : "billableItemList",
                forBillableItem : "forBillableItem",                       
                plan : "plan",                
                nonZoneBased : "Non Zone Based",
                zoneBased : "Zone Based",
                selectBillableItem : "Please select Billable Item!"
            },
            options : {                
                allZone    : "All Zone",
                selectZone : "Select Zone",
                nonZone : "Non Zone"
            },
            alerts : {
                alertLoading : "Alerts loading, please wait...",
                eventLoading : "Events loading, please wait...",
                notificationLoader : "Notifications loading, please wait...",
                grid : {
                    layout : {        
                        ip : "IP",
                        timeAddrerss : "Time Address",
                        attempt : "Attempt",
                        attemptFail : "Attempt Fail",
                        attemptSuccess : "Attempt Success"
                    }
                }
            },
            loader : {
                imageLoadError : "Cannot load image",
                loading : "Loading",
                jobLoading : "Jobs loading",
                loadingPleaseWait : "Loading please wait...",
                templateLoader : "Template loading, Please wait"
            },
            billing: {
                paid : "Paid",
                invoiceLoader : "Invoice loading, please wait",
                paymentLoader : "Payments loading, please wait",
                createVMToPayment : "Create an instance and make payment ",
                paymentSuccess : "Payment successful",
                paymentFailed : "Payment failed",
                cardAdded : "Card added!",
                taxName:"Tax Name",
                taxPercent : "Tax Percent",
                currentDue : "Current Due",
                billingCycle : "Billing Cycle",
                noOfUses : "No. of Uses",
                billingCycleUsed : "Applied billing cycle",
                cardNotVerified : "Card is not verified!",
                customItem : "CustomItem",
                recurringItem : "RecurringItem",    
                taxPercentage : "Tax Percentage",
                processingFee : "Processing Fee",
                grid : {
                    layout : {                                                                                                                            
                        invoiceNo : "Invoice No",
                        previousBalance : "Previous Balance",
                        payments : "Payments",
                        currentUsage : "Current Usage",
                        totalPayable : "Total Payable",
                        previousInvoiceDate : "Previous Invoice Date",
                        invoiceDate : "Invoice Date",                        
                        tokenNo :"Token No.",
                        paymentDate :"Payment Date",
                        amount :"Amount",
                        processingFee :"Processing Fee",
                        totalAmount :"Total Amount",
                        tockenNo:"Tocken No"
                    }
                }                
            }
        },
        ccAvenue : {
               none            : "None",
               andhraBankDebit : "Andhra Bank",
               canaraBankDebit : "Canara Bank",
               cityBankDebit   : "Citibank",
               iobDebit        : "Indian Overseas Bank",
               pnbDebitVisa    : "Punjab National Bank - VISA",
               pnbDebitMaster  : "Punjab National Bank - Master",
               ubiDebit        : "Union Bank of India",
               rupayDebit      : "RuPay Debit Cards",
               sbiDebit        : "State Bank of India",
               andhraNB        : "Andhra Bank",
               axisNB          : "Axis Bank",
               bobahrainNB     : "Bank of Bahrain & Kuwait",
               bobCorpNB       : "Bank of Baroda Corporate Accounts",
               bobRetailAcNB   : "Bank of Baroda Retail Accounts",
               boiNB           : "Bank of India",
               bomNB           : "Bank of Maharashtra",
               canNB           : "Canara Bank",
               catSyrNB        : "Catholic Syrian Bank",
               cenBINB         : "Central Bank of India",
               cityBankNB      : "Citibank Bank Account Online",
               cityUnionNB     : "City Union Bank",
               dbsBankNB       : "DBS Bank Ltd",
               dcbNB           : "DCB Bank ( Development Credit Bank )",
               deutscheNB      : "Deutsche Bank",
               dhanaNB         : "Dhanlaxmi Bank",
               federalNB       : "Federal Bank",
               hdfcNB          : "HDFC Bank",
               idbiNB          : "IDBI Bank",
               indNB           : "Indian Bank",
               iobNB           : "Indian Overseas Bank",
               indusNB         : "IndusInd Bank",
               ingNB           : "ING Vysya Bank",
               jkbNB           : "Jammu and Kashmir Bank",
               karnatakaNB     : "Karnataka Bank",
               kvbNB           : "Karur Vysya Bank",
               kotakNB         : "Kotak Mahindra Bank",
               lakshmiVilasNB  : "Lakshmi Vilas Bank NetBanking",
               orientalNB      : "Oriental Bank of Commerce",
               pnbCorpNB       : "Punjab National Bank Corporate Accounts",
               pnbRetailNB     : "Punjab National Bank Retail Accounts",
               rbsNB           : "RBS (The Royal Bank of Scotland)",
               sibNB           : "South Indian Bank",
               scbNB           : "Standard Chartered Bank",
               sbjNB           : "State Bank of Bikaner and Jaipur",
               sbhNB           : "State Bank of Hyderabad",
               sbiNB           : "State Bank of India",
               sbmNB           : "State Bank of Mysore",
               sbpNB           : "State Bank of Patiala",
               sbtNB           : "State Bank of Travancore",
               syndNB          : "Syndicate Bank",
               tnmNB           : "Tamilnad Mercantile Bank",
               ubiNB           : "Union Bank of India",
               unitedNB        : "United Bank of India",
               iCash           : "ICash Card",
               itzCash         : "Itz Cash / noQ 24x7",
               oxiCash         : "OxiCash Card",
               payCash         : "PayCash Card"
        },
        user : {
            userID : "User ID",
            userName : "Username",
            SSHKey : {
                SSHKeyDeleted : "SSH key deleted successfully",
                SSHKeyDeletedError : "Cannot delete SSH key! contact user",
                fingerPrint : "Finger Print",
                sshKeyCreated: "SSH key created successfully",
                cannotCreateSSHKey : "Cannot create SSH key! contact admin"
            },
            instance : {
              createInstance : "Create Instance"  
            },
            loader : {
                instanceLoader: "Loading instance, please wait...",
                volumeLoading : "Loading storage, please wait...",
                snapshotLoading : "Loading snapshot, please wait...",
                creatingVolume :  "Creating volume"
            },
            snapshot : {
                createSnapshot : "Create Snapshot",
                snapshotSuccess : "Snapshot Success",
                snapshotMessage : "You can update/delete your existing auto snapshot schedule jobs.",
                snapshotError : "Cannot Take Snapshot",  
                created : "Snapshot created successfully",
                deleted : "Snapshot deleted successfully",
                backedup : "BackedUp",
                snapshotUpdateSuccess : "snapshot config updated successfully",
                snapshotUpdateError :"Cannot updated snapshot config",
                deleteSnapshotFailed : "Failed to delete snapshot",
                volumeSnapshotMessage : "Click on the volume name you want to snapshot.",
                volumeAutoSnapshotMessage : "Click on the volume name you want to schedule auto snapshot on daily, weekly, monthly",
                vmSnapshot : {
                    vmSnapshotLoading : "Instance snapshot loading, please wait...",
                    cannotRevertVM : "Cannot revert instance snapshot! please contact admin",
                    revertVMSuccess : "Instance snapshot reverted successfully",
                    cannotDeleteVMSnapsot : "Cannot delete instance snapshot! please contact admin",
                    vmSnapshotDeletedSuccess : "Instance snapshot deleted successfully",
                    cannotCreateVmSnapshot : "Cannot create instance snapshot! please contact admin",
                    vmSnapshotCreated : "Instance snapshot created successfully",
                    vmSnapshotNotAvailable : "Instance snapshot is not availiable for trial account",
                    resizeVolume : "Resize Volume"
                }
            },
            storage : {
                name: "Storage",
                addedStorage : "Added storage",
                addVolumeError : "Cannot add volume",
                createdAndAttached : "Volume created and attached with instance successfully.",
                cannotDetached : "Cannot Detach",
                volumeLimitReached: "Volume limit reached!",
                notAttached : "Not attached",
                detachMessage : "please detach this volume from instance",
                cannotAttached : "Cannot attached",      
                volumeDeleted : "Cannot delete volume",
                volumeAttachedError : "Volume attached failed",       
                volumeDetachedFailed : "Failed to dettach volume , due to The instance rejected the attempt to detach the device",       
                deleteVolumeError : "Cannot delete this volume",
                storageDetached : "Volume detached successfully",
                volumeAttached : "Volume attached successfully",
                resizeError : "Cannot resize volume",
                upgradeSuccess : "Volume has been upgraded successfully",
                upgradeVolumeError : "You Cannot upgrate disk with this plan",
                createVMAddVolume : "Create a instance and add volume"
            },            
            grid : {
                instance : {
                    noInstance : "No Instance",
                    layout : {
                        vmName : "Instance Display Name",
                        plane  : "Plan",
                        ip     : "IP",
                        zone   : "Zone",
                        status : "Status",
                        action : "Action"                       
                    }
                },
                storage : {
                    noVolume : "You don't have any volumes yet. create one now.",
                    layout : {
                        diskName : "Disk Name",
                        plan : "Plan",
                        instanceAttached : "Instance attached",
                        size : "Size(GB)",
                        status : "Status",
                        action : "Action"
                    }
                },
                snapshot : {
                    noSnapshot : "There is no snapshot",
                    layout : {
                        snapshotName : "Snapshot Name",
                        volumeName : "Volume Name",
                        instanceName : "Instance Name",
                        type : "Type",
                        createdDate : "Created Date",
                        status : "Status",
                        action : "Action",
                        parentName : "Parent",
                        isCurrent : "isCurrent"
                    },
                    autoSnapshot : {
                        layout : {
                            time : "Time",
                            schedule : "Schedule",
                            timeZone : "Time Zone",
                            keep : "Keep",
                            action : "Action",
                            name : "Name",
                            diskName : "Disk Name",
                            type : "Type",
                            volumeType : "Volume Type",
                            snapshotConfig : "Snapshot Config"
                        }
                    }
                }
            }
        }
    },
    es: true   
});
